// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the app type in the database.
	Label = "app"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldImage holds the string denoting the image field in the database.
	FieldImage = "image"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldRepoURL holds the string denoting the repo_url field in the database.
	FieldRepoURL = "repo_url"
	// FieldBranch holds the string denoting the branch field in the database.
	FieldBranch = "branch"
	// EdgeSites holds the string denoting the sites edge name in mutations.
	EdgeSites = "sites"
	// EdgeContainers holds the string denoting the containers edge name in mutations.
	EdgeContainers = "containers"
	// EdgeDeploys holds the string denoting the deploys edge name in mutations.
	EdgeDeploys = "deploys"
	// EdgeEnvVars holds the string denoting the env_vars edge name in mutations.
	EdgeEnvVars = "env_vars"
	// EdgeCurrentContainer holds the string denoting the current_container edge name in mutations.
	EdgeCurrentContainer = "current_container"
	// Table holds the table name of the app in the database.
	Table = "apps"
	// SitesTable is the table that holds the sites relation/edge.
	SitesTable = "sites"
	// SitesInverseTable is the table name for the Site entity.
	// It exists in this package in order to avoid circular dependency with the "site" package.
	SitesInverseTable = "sites"
	// SitesColumn is the table column denoting the sites relation/edge.
	SitesColumn = "app_sites"
	// ContainersTable is the table that holds the containers relation/edge.
	ContainersTable = "containers"
	// ContainersInverseTable is the table name for the Container entity.
	// It exists in this package in order to avoid circular dependency with the "container" package.
	ContainersInverseTable = "containers"
	// ContainersColumn is the table column denoting the containers relation/edge.
	ContainersColumn = "app_containers"
	// DeploysTable is the table that holds the deploys relation/edge.
	DeploysTable = "deploys"
	// DeploysInverseTable is the table name for the Deploy entity.
	// It exists in this package in order to avoid circular dependency with the "deploy" package.
	DeploysInverseTable = "deploys"
	// DeploysColumn is the table column denoting the deploys relation/edge.
	DeploysColumn = "app_deploys"
	// EnvVarsTable is the table that holds the env_vars relation/edge.
	EnvVarsTable = "env_vars"
	// EnvVarsInverseTable is the table name for the EnvVar entity.
	// It exists in this package in order to avoid circular dependency with the "envvar" package.
	EnvVarsInverseTable = "env_vars"
	// EnvVarsColumn is the table column denoting the env_vars relation/edge.
	EnvVarsColumn = "app_env_vars"
	// CurrentContainerTable is the table that holds the current_container relation/edge.
	CurrentContainerTable = "containers"
	// CurrentContainerInverseTable is the table name for the Container entity.
	// It exists in this package in order to avoid circular dependency with the "container" package.
	CurrentContainerInverseTable = "containers"
	// CurrentContainerColumn is the table column denoting the current_container relation/edge.
	CurrentContainerColumn = "app_current_container"
)

// Columns holds all SQL columns for app fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldImage,
	FieldPort,
	FieldRepoURL,
	FieldBranch,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// PortValidator is a validator for the "port" field. It is called by the builders before save.
	PortValidator func(int) error
	// DefaultBranch holds the default value on creation for the "branch" field.
	DefaultBranch string
)

// OrderOption defines the ordering options for the App queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByImage orders the results by the image field.
func ByImage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldImage, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByRepoURL orders the results by the repo_url field.
func ByRepoURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoURL, opts...).ToFunc()
}

// ByBranch orders the results by the branch field.
func ByBranch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBranch, opts...).ToFunc()
}

// BySitesCount orders the results by sites count.
func BySitesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSitesStep(), opts...)
	}
}

// BySites orders the results by sites terms.
func BySites(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSitesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByContainersCount orders the results by containers count.
func ByContainersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newContainersStep(), opts...)
	}
}

// ByContainers orders the results by containers terms.
func ByContainers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newContainersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByDeploysCount orders the results by deploys count.
func ByDeploysCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDeploysStep(), opts...)
	}
}

// ByDeploys orders the results by deploys terms.
func ByDeploys(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDeploysStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByEnvVarsCount orders the results by env_vars count.
func ByEnvVarsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newEnvVarsStep(), opts...)
	}
}

// ByEnvVars orders the results by env_vars terms.
func ByEnvVars(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newEnvVarsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCurrentContainerField orders the results by current_container field.
func ByCurrentContainerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCurrentContainerStep(), sql.OrderByField(field, opts...))
	}
}
func newSitesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SitesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SitesTable, SitesColumn),
	)
}
func newContainersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ContainersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ContainersTable, ContainersColumn),
	)
}
func newDeploysStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DeploysInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, DeploysTable, DeploysColumn),
	)
}
func newEnvVarsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(EnvVarsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, EnvVarsTable, EnvVarsColumn),
	)
}
func newCurrentContainerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CurrentContainerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, false, CurrentContainerTable, CurrentContainerColumn),
	)
}
