// Code generated by ent, DO NOT EDIT.

package app

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.App {
	return predicate.App(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.App {
	return predicate.App(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldImage, v))
}

// Port applies equality check predicate on the "port" field. It's identical to PortEQ.
func Port(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldPort, v))
}

// RepoURL applies equality check predicate on the "repo_url" field. It's identical to RepoURLEQ.
func RepoURL(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRepoURL, v))
}

// Branch applies equality check predicate on the "branch" field. It's identical to BranchEQ.
func Branch(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldBranch, v))
}

// DeployMethod applies equality check predicate on the "deploy_method" field. It's identical to DeployMethodEQ.
func DeployMethod(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDeployMethod, v))
}

// ComposeContent applies equality check predicate on the "compose_content" field. It's identical to ComposeContentEQ.
func ComposeContent(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldComposeContent, v))
}

// ComposePath applies equality check predicate on the "compose_path" field. It's identical to ComposePathEQ.
func ComposePath(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldComposePath, v))
}

// RegistryURL applies equality check predicate on the "registry_url" field. It's identical to RegistryURLEQ.
func RegistryURL(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryURL, v))
}

// RegistryUsername applies equality check predicate on the "registry_username" field. It's identical to RegistryUsernameEQ.
func RegistryUsername(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryUsername, v))
}

// RegistryPassword applies equality check predicate on the "registry_password" field. It's identical to RegistryPasswordEQ.
func RegistryPassword(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryPassword, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.App {
	return predicate.App(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.App {
	return predicate.App(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.App {
	return predicate.App(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldName, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldImage, v))
}

// ImageIsNil applies the IsNil predicate on the "image" field.
func ImageIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldImage))
}

// ImageNotNil applies the NotNil predicate on the "image" field.
func ImageNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldImage))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldImage, v))
}

// PortEQ applies the EQ predicate on the "port" field.
func PortEQ(v int) predicate.App {
	return predicate.App(sql.FieldEQ(FieldPort, v))
}

// PortNEQ applies the NEQ predicate on the "port" field.
func PortNEQ(v int) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldPort, v))
}

// PortIn applies the In predicate on the "port" field.
func PortIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldIn(FieldPort, vs...))
}

// PortNotIn applies the NotIn predicate on the "port" field.
func PortNotIn(vs ...int) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldPort, vs...))
}

// PortGT applies the GT predicate on the "port" field.
func PortGT(v int) predicate.App {
	return predicate.App(sql.FieldGT(FieldPort, v))
}

// PortGTE applies the GTE predicate on the "port" field.
func PortGTE(v int) predicate.App {
	return predicate.App(sql.FieldGTE(FieldPort, v))
}

// PortLT applies the LT predicate on the "port" field.
func PortLT(v int) predicate.App {
	return predicate.App(sql.FieldLT(FieldPort, v))
}

// PortLTE applies the LTE predicate on the "port" field.
func PortLTE(v int) predicate.App {
	return predicate.App(sql.FieldLTE(FieldPort, v))
}

// PortIsNil applies the IsNil predicate on the "port" field.
func PortIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldPort))
}

// PortNotNil applies the NotNil predicate on the "port" field.
func PortNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldPort))
}

// RepoURLEQ applies the EQ predicate on the "repo_url" field.
func RepoURLEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRepoURL, v))
}

// RepoURLNEQ applies the NEQ predicate on the "repo_url" field.
func RepoURLNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRepoURL, v))
}

// RepoURLIn applies the In predicate on the "repo_url" field.
func RepoURLIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldRepoURL, vs...))
}

// RepoURLNotIn applies the NotIn predicate on the "repo_url" field.
func RepoURLNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRepoURL, vs...))
}

// RepoURLGT applies the GT predicate on the "repo_url" field.
func RepoURLGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldRepoURL, v))
}

// RepoURLGTE applies the GTE predicate on the "repo_url" field.
func RepoURLGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRepoURL, v))
}

// RepoURLLT applies the LT predicate on the "repo_url" field.
func RepoURLLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldRepoURL, v))
}

// RepoURLLTE applies the LTE predicate on the "repo_url" field.
func RepoURLLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRepoURL, v))
}

// RepoURLContains applies the Contains predicate on the "repo_url" field.
func RepoURLContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldRepoURL, v))
}

// RepoURLHasPrefix applies the HasPrefix predicate on the "repo_url" field.
func RepoURLHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldRepoURL, v))
}

// RepoURLHasSuffix applies the HasSuffix predicate on the "repo_url" field.
func RepoURLHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldRepoURL, v))
}

// RepoURLIsNil applies the IsNil predicate on the "repo_url" field.
func RepoURLIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRepoURL))
}

// RepoURLNotNil applies the NotNil predicate on the "repo_url" field.
func RepoURLNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRepoURL))
}

// RepoURLEqualFold applies the EqualFold predicate on the "repo_url" field.
func RepoURLEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldRepoURL, v))
}

// RepoURLContainsFold applies the ContainsFold predicate on the "repo_url" field.
func RepoURLContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldRepoURL, v))
}

// BranchEQ applies the EQ predicate on the "branch" field.
func BranchEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldBranch, v))
}

// BranchNEQ applies the NEQ predicate on the "branch" field.
func BranchNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldBranch, v))
}

// BranchIn applies the In predicate on the "branch" field.
func BranchIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldBranch, vs...))
}

// BranchNotIn applies the NotIn predicate on the "branch" field.
func BranchNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldBranch, vs...))
}

// BranchGT applies the GT predicate on the "branch" field.
func BranchGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldBranch, v))
}

// BranchGTE applies the GTE predicate on the "branch" field.
func BranchGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldBranch, v))
}

// BranchLT applies the LT predicate on the "branch" field.
func BranchLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldBranch, v))
}

// BranchLTE applies the LTE predicate on the "branch" field.
func BranchLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldBranch, v))
}

// BranchContains applies the Contains predicate on the "branch" field.
func BranchContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldBranch, v))
}

// BranchHasPrefix applies the HasPrefix predicate on the "branch" field.
func BranchHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldBranch, v))
}

// BranchHasSuffix applies the HasSuffix predicate on the "branch" field.
func BranchHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldBranch, v))
}

// BranchEqualFold applies the EqualFold predicate on the "branch" field.
func BranchEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldBranch, v))
}

// BranchContainsFold applies the ContainsFold predicate on the "branch" field.
func BranchContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldBranch, v))
}

// DeployMethodEQ applies the EQ predicate on the "deploy_method" field.
func DeployMethodEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldDeployMethod, v))
}

// DeployMethodNEQ applies the NEQ predicate on the "deploy_method" field.
func DeployMethodNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldDeployMethod, v))
}

// DeployMethodIn applies the In predicate on the "deploy_method" field.
func DeployMethodIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldDeployMethod, vs...))
}

// DeployMethodNotIn applies the NotIn predicate on the "deploy_method" field.
func DeployMethodNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldDeployMethod, vs...))
}

// DeployMethodGT applies the GT predicate on the "deploy_method" field.
func DeployMethodGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldDeployMethod, v))
}

// DeployMethodGTE applies the GTE predicate on the "deploy_method" field.
func DeployMethodGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldDeployMethod, v))
}

// DeployMethodLT applies the LT predicate on the "deploy_method" field.
func DeployMethodLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldDeployMethod, v))
}

// DeployMethodLTE applies the LTE predicate on the "deploy_method" field.
func DeployMethodLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldDeployMethod, v))
}

// DeployMethodContains applies the Contains predicate on the "deploy_method" field.
func DeployMethodContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldDeployMethod, v))
}

// DeployMethodHasPrefix applies the HasPrefix predicate on the "deploy_method" field.
func DeployMethodHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldDeployMethod, v))
}

// DeployMethodHasSuffix applies the HasSuffix predicate on the "deploy_method" field.
func DeployMethodHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldDeployMethod, v))
}

// DeployMethodEqualFold applies the EqualFold predicate on the "deploy_method" field.
func DeployMethodEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldDeployMethod, v))
}

// DeployMethodContainsFold applies the ContainsFold predicate on the "deploy_method" field.
func DeployMethodContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldDeployMethod, v))
}

// ComposeContentEQ applies the EQ predicate on the "compose_content" field.
func ComposeContentEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldComposeContent, v))
}

// ComposeContentNEQ applies the NEQ predicate on the "compose_content" field.
func ComposeContentNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldComposeContent, v))
}

// ComposeContentIn applies the In predicate on the "compose_content" field.
func ComposeContentIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldComposeContent, vs...))
}

// ComposeContentNotIn applies the NotIn predicate on the "compose_content" field.
func ComposeContentNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldComposeContent, vs...))
}

// ComposeContentGT applies the GT predicate on the "compose_content" field.
func ComposeContentGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldComposeContent, v))
}

// ComposeContentGTE applies the GTE predicate on the "compose_content" field.
func ComposeContentGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldComposeContent, v))
}

// ComposeContentLT applies the LT predicate on the "compose_content" field.
func ComposeContentLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldComposeContent, v))
}

// ComposeContentLTE applies the LTE predicate on the "compose_content" field.
func ComposeContentLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldComposeContent, v))
}

// ComposeContentContains applies the Contains predicate on the "compose_content" field.
func ComposeContentContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldComposeContent, v))
}

// ComposeContentHasPrefix applies the HasPrefix predicate on the "compose_content" field.
func ComposeContentHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldComposeContent, v))
}

// ComposeContentHasSuffix applies the HasSuffix predicate on the "compose_content" field.
func ComposeContentHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldComposeContent, v))
}

// ComposeContentIsNil applies the IsNil predicate on the "compose_content" field.
func ComposeContentIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldComposeContent))
}

// ComposeContentNotNil applies the NotNil predicate on the "compose_content" field.
func ComposeContentNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldComposeContent))
}

// ComposeContentEqualFold applies the EqualFold predicate on the "compose_content" field.
func ComposeContentEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldComposeContent, v))
}

// ComposeContentContainsFold applies the ContainsFold predicate on the "compose_content" field.
func ComposeContentContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldComposeContent, v))
}

// ComposePathEQ applies the EQ predicate on the "compose_path" field.
func ComposePathEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldComposePath, v))
}

// ComposePathNEQ applies the NEQ predicate on the "compose_path" field.
func ComposePathNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldComposePath, v))
}

// ComposePathIn applies the In predicate on the "compose_path" field.
func ComposePathIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldComposePath, vs...))
}

// ComposePathNotIn applies the NotIn predicate on the "compose_path" field.
func ComposePathNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldComposePath, vs...))
}

// ComposePathGT applies the GT predicate on the "compose_path" field.
func ComposePathGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldComposePath, v))
}

// ComposePathGTE applies the GTE predicate on the "compose_path" field.
func ComposePathGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldComposePath, v))
}

// ComposePathLT applies the LT predicate on the "compose_path" field.
func ComposePathLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldComposePath, v))
}

// ComposePathLTE applies the LTE predicate on the "compose_path" field.
func ComposePathLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldComposePath, v))
}

// ComposePathContains applies the Contains predicate on the "compose_path" field.
func ComposePathContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldComposePath, v))
}

// ComposePathHasPrefix applies the HasPrefix predicate on the "compose_path" field.
func ComposePathHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldComposePath, v))
}

// ComposePathHasSuffix applies the HasSuffix predicate on the "compose_path" field.
func ComposePathHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldComposePath, v))
}

// ComposePathIsNil applies the IsNil predicate on the "compose_path" field.
func ComposePathIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldComposePath))
}

// ComposePathNotNil applies the NotNil predicate on the "compose_path" field.
func ComposePathNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldComposePath))
}

// ComposePathEqualFold applies the EqualFold predicate on the "compose_path" field.
func ComposePathEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldComposePath, v))
}

// ComposePathContainsFold applies the ContainsFold predicate on the "compose_path" field.
func ComposePathContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldComposePath, v))
}

// RegistryURLEQ applies the EQ predicate on the "registry_url" field.
func RegistryURLEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryURL, v))
}

// RegistryURLNEQ applies the NEQ predicate on the "registry_url" field.
func RegistryURLNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRegistryURL, v))
}

// RegistryURLIn applies the In predicate on the "registry_url" field.
func RegistryURLIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldRegistryURL, vs...))
}

// RegistryURLNotIn applies the NotIn predicate on the "registry_url" field.
func RegistryURLNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRegistryURL, vs...))
}

// RegistryURLGT applies the GT predicate on the "registry_url" field.
func RegistryURLGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldRegistryURL, v))
}

// RegistryURLGTE applies the GTE predicate on the "registry_url" field.
func RegistryURLGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRegistryURL, v))
}

// RegistryURLLT applies the LT predicate on the "registry_url" field.
func RegistryURLLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldRegistryURL, v))
}

// RegistryURLLTE applies the LTE predicate on the "registry_url" field.
func RegistryURLLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRegistryURL, v))
}

// RegistryURLContains applies the Contains predicate on the "registry_url" field.
func RegistryURLContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldRegistryURL, v))
}

// RegistryURLHasPrefix applies the HasPrefix predicate on the "registry_url" field.
func RegistryURLHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldRegistryURL, v))
}

// RegistryURLHasSuffix applies the HasSuffix predicate on the "registry_url" field.
func RegistryURLHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldRegistryURL, v))
}

// RegistryURLIsNil applies the IsNil predicate on the "registry_url" field.
func RegistryURLIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRegistryURL))
}

// RegistryURLNotNil applies the NotNil predicate on the "registry_url" field.
func RegistryURLNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRegistryURL))
}

// RegistryURLEqualFold applies the EqualFold predicate on the "registry_url" field.
func RegistryURLEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldRegistryURL, v))
}

// RegistryURLContainsFold applies the ContainsFold predicate on the "registry_url" field.
func RegistryURLContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldRegistryURL, v))
}

// RegistryUsernameEQ applies the EQ predicate on the "registry_username" field.
func RegistryUsernameEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryUsername, v))
}

// RegistryUsernameNEQ applies the NEQ predicate on the "registry_username" field.
func RegistryUsernameNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRegistryUsername, v))
}

// RegistryUsernameIn applies the In predicate on the "registry_username" field.
func RegistryUsernameIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldRegistryUsername, vs...))
}

// RegistryUsernameNotIn applies the NotIn predicate on the "registry_username" field.
func RegistryUsernameNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRegistryUsername, vs...))
}

// RegistryUsernameGT applies the GT predicate on the "registry_username" field.
func RegistryUsernameGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldRegistryUsername, v))
}

// RegistryUsernameGTE applies the GTE predicate on the "registry_username" field.
func RegistryUsernameGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRegistryUsername, v))
}

// RegistryUsernameLT applies the LT predicate on the "registry_username" field.
func RegistryUsernameLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldRegistryUsername, v))
}

// RegistryUsernameLTE applies the LTE predicate on the "registry_username" field.
func RegistryUsernameLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRegistryUsername, v))
}

// RegistryUsernameContains applies the Contains predicate on the "registry_username" field.
func RegistryUsernameContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldRegistryUsername, v))
}

// RegistryUsernameHasPrefix applies the HasPrefix predicate on the "registry_username" field.
func RegistryUsernameHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldRegistryUsername, v))
}

// RegistryUsernameHasSuffix applies the HasSuffix predicate on the "registry_username" field.
func RegistryUsernameHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldRegistryUsername, v))
}

// RegistryUsernameIsNil applies the IsNil predicate on the "registry_username" field.
func RegistryUsernameIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRegistryUsername))
}

// RegistryUsernameNotNil applies the NotNil predicate on the "registry_username" field.
func RegistryUsernameNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRegistryUsername))
}

// RegistryUsernameEqualFold applies the EqualFold predicate on the "registry_username" field.
func RegistryUsernameEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldRegistryUsername, v))
}

// RegistryUsernameContainsFold applies the ContainsFold predicate on the "registry_username" field.
func RegistryUsernameContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldRegistryUsername, v))
}

// RegistryPasswordEQ applies the EQ predicate on the "registry_password" field.
func RegistryPasswordEQ(v string) predicate.App {
	return predicate.App(sql.FieldEQ(FieldRegistryPassword, v))
}

// RegistryPasswordNEQ applies the NEQ predicate on the "registry_password" field.
func RegistryPasswordNEQ(v string) predicate.App {
	return predicate.App(sql.FieldNEQ(FieldRegistryPassword, v))
}

// RegistryPasswordIn applies the In predicate on the "registry_password" field.
func RegistryPasswordIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldIn(FieldRegistryPassword, vs...))
}

// RegistryPasswordNotIn applies the NotIn predicate on the "registry_password" field.
func RegistryPasswordNotIn(vs ...string) predicate.App {
	return predicate.App(sql.FieldNotIn(FieldRegistryPassword, vs...))
}

// RegistryPasswordGT applies the GT predicate on the "registry_password" field.
func RegistryPasswordGT(v string) predicate.App {
	return predicate.App(sql.FieldGT(FieldRegistryPassword, v))
}

// RegistryPasswordGTE applies the GTE predicate on the "registry_password" field.
func RegistryPasswordGTE(v string) predicate.App {
	return predicate.App(sql.FieldGTE(FieldRegistryPassword, v))
}

// RegistryPasswordLT applies the LT predicate on the "registry_password" field.
func RegistryPasswordLT(v string) predicate.App {
	return predicate.App(sql.FieldLT(FieldRegistryPassword, v))
}

// RegistryPasswordLTE applies the LTE predicate on the "registry_password" field.
func RegistryPasswordLTE(v string) predicate.App {
	return predicate.App(sql.FieldLTE(FieldRegistryPassword, v))
}

// RegistryPasswordContains applies the Contains predicate on the "registry_password" field.
func RegistryPasswordContains(v string) predicate.App {
	return predicate.App(sql.FieldContains(FieldRegistryPassword, v))
}

// RegistryPasswordHasPrefix applies the HasPrefix predicate on the "registry_password" field.
func RegistryPasswordHasPrefix(v string) predicate.App {
	return predicate.App(sql.FieldHasPrefix(FieldRegistryPassword, v))
}

// RegistryPasswordHasSuffix applies the HasSuffix predicate on the "registry_password" field.
func RegistryPasswordHasSuffix(v string) predicate.App {
	return predicate.App(sql.FieldHasSuffix(FieldRegistryPassword, v))
}

// RegistryPasswordIsNil applies the IsNil predicate on the "registry_password" field.
func RegistryPasswordIsNil() predicate.App {
	return predicate.App(sql.FieldIsNull(FieldRegistryPassword))
}

// RegistryPasswordNotNil applies the NotNil predicate on the "registry_password" field.
func RegistryPasswordNotNil() predicate.App {
	return predicate.App(sql.FieldNotNull(FieldRegistryPassword))
}

// RegistryPasswordEqualFold applies the EqualFold predicate on the "registry_password" field.
func RegistryPasswordEqualFold(v string) predicate.App {
	return predicate.App(sql.FieldEqualFold(FieldRegistryPassword, v))
}

// RegistryPasswordContainsFold applies the ContainsFold predicate on the "registry_password" field.
func RegistryPasswordContainsFold(v string) predicate.App {
	return predicate.App(sql.FieldContainsFold(FieldRegistryPassword, v))
}

// HasSites applies the HasEdge predicate on the "sites" edge.
func HasSites() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SitesTable, SitesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSitesWith applies the HasEdge predicate on the "sites" edge with a given conditions (other predicates).
func HasSitesWith(preds ...predicate.Site) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newSitesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContainers applies the HasEdge predicate on the "containers" edge.
func HasContainers() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ContainersTable, ContainersColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContainersWith applies the HasEdge predicate on the "containers" edge with a given conditions (other predicates).
func HasContainersWith(preds ...predicate.Container) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newContainersStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeploys applies the HasEdge predicate on the "deploys" edge.
func HasDeploys() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, DeploysTable, DeploysColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeploysWith applies the HasEdge predicate on the "deploys" edge with a given conditions (other predicates).
func HasDeploysWith(preds ...predicate.Deploy) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newDeploysStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasEnvVars applies the HasEdge predicate on the "env_vars" edge.
func HasEnvVars() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, EnvVarsTable, EnvVarsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasEnvVarsWith applies the HasEdge predicate on the "env_vars" edge with a given conditions (other predicates).
func HasEnvVarsWith(preds ...predicate.EnvVar) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newEnvVarsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrentContainer applies the HasEdge predicate on the "current_container" edge.
func HasCurrentContainer() predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, CurrentContainerTable, CurrentContainerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrentContainerWith applies the HasEdge predicate on the "current_container" edge with a given conditions (other predicates).
func HasCurrentContainerWith(preds ...predicate.Container) predicate.App {
	return predicate.App(func(s *sql.Selector) {
		step := newCurrentContainerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.App) predicate.App {
	return predicate.App(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.App) predicate.App {
	return predicate.App(sql.NotPredicates(p))
}
