// Code generated by ent, DO NOT EDIT.

package site

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpdatedAt, v))
}

// Domain applies equality check predicate on the "domain" field. It's identical to DomainEQ.
func Domain(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldDomain, v))
}

// Upstream applies equality check predicate on the "upstream" field. It's identical to UpstreamEQ.
func Upstream(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpstream, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldEnabled, v))
}

// AppService applies equality check predicate on the "app_service" field. It's identical to AppServiceEQ.
func AppService(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAppService, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldUpdatedAt, v))
}

// DomainEQ applies the EQ predicate on the "domain" field.
func DomainEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldDomain, v))
}

// DomainNEQ applies the NEQ predicate on the "domain" field.
func DomainNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldDomain, v))
}

// DomainIn applies the In predicate on the "domain" field.
func DomainIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldDomain, vs...))
}

// DomainNotIn applies the NotIn predicate on the "domain" field.
func DomainNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldDomain, vs...))
}

// DomainGT applies the GT predicate on the "domain" field.
func DomainGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldDomain, v))
}

// DomainGTE applies the GTE predicate on the "domain" field.
func DomainGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldDomain, v))
}

// DomainLT applies the LT predicate on the "domain" field.
func DomainLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldDomain, v))
}

// DomainLTE applies the LTE predicate on the "domain" field.
func DomainLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldDomain, v))
}

// DomainContains applies the Contains predicate on the "domain" field.
func DomainContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldDomain, v))
}

// DomainHasPrefix applies the HasPrefix predicate on the "domain" field.
func DomainHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldDomain, v))
}

// DomainHasSuffix applies the HasSuffix predicate on the "domain" field.
func DomainHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldDomain, v))
}

// DomainEqualFold applies the EqualFold predicate on the "domain" field.
func DomainEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldDomain, v))
}

// DomainContainsFold applies the ContainsFold predicate on the "domain" field.
func DomainContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldDomain, v))
}

// UpstreamEQ applies the EQ predicate on the "upstream" field.
func UpstreamEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldUpstream, v))
}

// UpstreamNEQ applies the NEQ predicate on the "upstream" field.
func UpstreamNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldUpstream, v))
}

// UpstreamIn applies the In predicate on the "upstream" field.
func UpstreamIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldUpstream, vs...))
}

// UpstreamNotIn applies the NotIn predicate on the "upstream" field.
func UpstreamNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldUpstream, vs...))
}

// UpstreamGT applies the GT predicate on the "upstream" field.
func UpstreamGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldUpstream, v))
}

// UpstreamGTE applies the GTE predicate on the "upstream" field.
func UpstreamGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldUpstream, v))
}

// UpstreamLT applies the LT predicate on the "upstream" field.
func UpstreamLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldUpstream, v))
}

// UpstreamLTE applies the LTE predicate on the "upstream" field.
func UpstreamLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldUpstream, v))
}

// UpstreamContains applies the Contains predicate on the "upstream" field.
func UpstreamContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldUpstream, v))
}

// UpstreamHasPrefix applies the HasPrefix predicate on the "upstream" field.
func UpstreamHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldUpstream, v))
}

// UpstreamHasSuffix applies the HasSuffix predicate on the "upstream" field.
func UpstreamHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldUpstream, v))
}

// UpstreamIsNil applies the IsNil predicate on the "upstream" field.
func UpstreamIsNil() predicate.Site {
	return predicate.Site(sql.FieldIsNull(FieldUpstream))
}

// UpstreamNotNil applies the NotNil predicate on the "upstream" field.
func UpstreamNotNil() predicate.Site {
	return predicate.Site(sql.FieldNotNull(FieldUpstream))
}

// UpstreamEqualFold applies the EqualFold predicate on the "upstream" field.
func UpstreamEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldUpstream, v))
}

// UpstreamContainsFold applies the ContainsFold predicate on the "upstream" field.
func UpstreamContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldUpstream, v))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldEnabled, v))
}

// SchemeEQ applies the EQ predicate on the "scheme" field.
func SchemeEQ(v Scheme) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldScheme, v))
}

// SchemeNEQ applies the NEQ predicate on the "scheme" field.
func SchemeNEQ(v Scheme) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldScheme, v))
}

// SchemeIn applies the In predicate on the "scheme" field.
func SchemeIn(vs ...Scheme) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldScheme, vs...))
}

// SchemeNotIn applies the NotIn predicate on the "scheme" field.
func SchemeNotIn(vs ...Scheme) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldScheme, vs...))
}

// AppServiceEQ applies the EQ predicate on the "app_service" field.
func AppServiceEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldEQ(FieldAppService, v))
}

// AppServiceNEQ applies the NEQ predicate on the "app_service" field.
func AppServiceNEQ(v string) predicate.Site {
	return predicate.Site(sql.FieldNEQ(FieldAppService, v))
}

// AppServiceIn applies the In predicate on the "app_service" field.
func AppServiceIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldIn(FieldAppService, vs...))
}

// AppServiceNotIn applies the NotIn predicate on the "app_service" field.
func AppServiceNotIn(vs ...string) predicate.Site {
	return predicate.Site(sql.FieldNotIn(FieldAppService, vs...))
}

// AppServiceGT applies the GT predicate on the "app_service" field.
func AppServiceGT(v string) predicate.Site {
	return predicate.Site(sql.FieldGT(FieldAppService, v))
}

// AppServiceGTE applies the GTE predicate on the "app_service" field.
func AppServiceGTE(v string) predicate.Site {
	return predicate.Site(sql.FieldGTE(FieldAppService, v))
}

// AppServiceLT applies the LT predicate on the "app_service" field.
func AppServiceLT(v string) predicate.Site {
	return predicate.Site(sql.FieldLT(FieldAppService, v))
}

// AppServiceLTE applies the LTE predicate on the "app_service" field.
func AppServiceLTE(v string) predicate.Site {
	return predicate.Site(sql.FieldLTE(FieldAppService, v))
}

// AppServiceContains applies the Contains predicate on the "app_service" field.
func AppServiceContains(v string) predicate.Site {
	return predicate.Site(sql.FieldContains(FieldAppService, v))
}

// AppServiceHasPrefix applies the HasPrefix predicate on the "app_service" field.
func AppServiceHasPrefix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasPrefix(FieldAppService, v))
}

// AppServiceHasSuffix applies the HasSuffix predicate on the "app_service" field.
func AppServiceHasSuffix(v string) predicate.Site {
	return predicate.Site(sql.FieldHasSuffix(FieldAppService, v))
}

// AppServiceIsNil applies the IsNil predicate on the "app_service" field.
func AppServiceIsNil() predicate.Site {
	return predicate.Site(sql.FieldIsNull(FieldAppService))
}

// AppServiceNotNil applies the NotNil predicate on the "app_service" field.
func AppServiceNotNil() predicate.Site {
	return predicate.Site(sql.FieldNotNull(FieldAppService))
}

// AppServiceEqualFold applies the EqualFold predicate on the "app_service" field.
func AppServiceEqualFold(v string) predicate.Site {
	return predicate.Site(sql.FieldEqualFold(FieldAppService, v))
}

// AppServiceContainsFold applies the ContainsFold predicate on the "app_service" field.
func AppServiceContainsFold(v string) predicate.Site {
	return predicate.Site(sql.FieldContainsFold(FieldAppService, v))
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.App) predicate.Site {
	return predicate.Site(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Site) predicate.Site {
	return predicate.Site(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Site) predicate.Site {
	return predicate.Site(sql.NotPredicates(p))
}
