package caddy

import (
	"strings"
	"testing"

	"github.com/isaced/nanoku/internal/db"
	sitepkg "github.com/isaced/nanoku/internal/db/site"
)

func TestRender_EmptySites(t *testing.T) {
	out := Render(nil, "")
	if !strings.Contains(out, "Auto-generated by Nanoku") {
		t.Errorf("missing header comment, got:\n%s", out)
	}
	if strings.Contains(out, "auto_https off") {
		t.Errorf("default should keep auto-HTTPS on, got:\n%s", out)
	}
}

func TestRender_DisabledSitesAreSkipped(t *testing.T) {
	sites := []*db.Site{
		{Domain: "a.example.com", Upstream: "app:3000", Scheme: sitepkg.SchemeHTTPS, Enabled: true},
		{Domain: "b.example.com", Upstream: "app:3001", Scheme: sitepkg.SchemeHTTPS, Enabled: false},
	}
	out := Render(sites, "")
	if !strings.Contains(out, "a.example.com") {
		t.Errorf("enabled site missing:\n%s", out)
	}
	if strings.Contains(out, "b.example.com") {
		t.Errorf("disabled site must be skipped:\n%s", out)
	}
}

func TestRender_SortsByDomain(t *testing.T) {
	sites := []*db.Site{
		{Domain: "zeta.example.com", Upstream: "a:1", Scheme: sitepkg.SchemeHTTPS, Enabled: true},
		{Domain: "alpha.example.com", Upstream: "a:2", Scheme: sitepkg.SchemeHTTPS, Enabled: true},
		{Domain: "mike.example.com", Upstream: "a:3", Scheme: sitepkg.SchemeHTTPS, Enabled: true},
	}
	out := Render(sites, "")
	zi := strings.Index(out, "zeta")
	ai := strings.Index(out, "alpha")
	mi := strings.Index(out, "mike")
	if !(ai < mi && mi < zi) {
		t.Errorf("expected alpha < mike < zeta, got indexes %d/%d/%d in:\n%s", ai, mi, zi, out)
	}
}

func TestRender_ACMEEmail(t *testing.T) {
	out := Render(nil, "ops@example.com")
	if !strings.Contains(out, "email ops@example.com") {
		t.Errorf("acme email not rendered:\n%s", out)
	}
}

func TestRender_HTTPSSiteUsesDefaultHTTPS(t *testing.T) {
	out := Render([]*db.Site{{Domain: "x.example.com", Upstream: "app:80", Scheme: sitepkg.SchemeHTTPS, Enabled: true}}, "")
	if strings.Contains(out, "auto_https off") {
		t.Errorf("auto_https should NOT be off by default:\n%s", out)
	}
	if strings.Contains(out, "http://x.example.com") {
		t.Errorf("https site should not force http:// scheme:\n%s", out)
	}
	if !strings.Contains(out, "reverse_proxy app:80") {
		t.Errorf("upstream missing:\n%s", out)
	}
}

func TestRender_HTTPSiteForcesHTTPScheme(t *testing.T) {
	out := Render([]*db.Site{{Domain: "x.example.com", Upstream: "app:80", Scheme: sitepkg.SchemeHTTP, Enabled: true}}, "")
	if !strings.Contains(out, "http://x.example.com") {
		t.Errorf("http site should force http:// scheme:\n%s", out)
	}
	if !strings.Contains(out, "reverse_proxy app:80") {
		t.Errorf("upstream missing:\n%s", out)
	}
}

func TestRender_AutoHTTPSGloballyOff(t *testing.T) {
	t.Setenv("NANOKU_CADDY_AUTO_HTTPS", "false")
	out := Render([]*db.Site{
		{Domain: "a.example.com", Upstream: "app:1", Scheme: sitepkg.SchemeHTTPS, Enabled: true},
		{Domain: "b.example.com", Upstream: "app:2", Scheme: sitepkg.SchemeHTTP, Enabled: true},
	}, "")
	if !strings.Contains(out, "auto_https off") {
		t.Errorf("env=false should emit global auto_https off block:\n%s", out)
	}
	// https site no longer needs http:// prefix when global auto_https is off
	if strings.Contains(out, "http://a.example.com") {
		t.Errorf("https site under global auto_https off should not force http://:\n%s", out)
	}
	// http site still gets http:// prefix to ensure :80 binding
	if !strings.Contains(out, "http://b.example.com") {
		t.Errorf("http site should keep http:// scheme even under global off:\n%s", out)
	}
}
