package caddy

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/isaced/nanoku/internal/db"
)

func Render(sites []*db.Site, acmeEmail string) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by Nanoku. Do not edit.\n")
	b.WriteString("# Regenerated on every Site change.\n\n")

	// If any enabled site is on a loopback address (localhost, 127.0.0.1,
	// ::1, *.localhost), Caddy cannot issue a real ACME cert for it — and
	// will keep retrying and failing every reload. Disable auto-HTTPS at
	// the global level whenever that's the case so the file stays valid.
	hasLoopback := false
	for _, s := range sites {
		if s.Enabled && IsLoopbackDomain(s.Domain) {
			hasLoopback = true
			break
		}
	}

	// Global options. By default Caddy uses auto-HTTPS (issues/renews certs).
	// Disable it either via NANOKU_CADDY_AUTO_HTTPS=false (full opt-out) or
	// implicitly when a loopback site forces it.
	if !autoHTTPSEnabled() || hasLoopback {
		b.WriteString("{\n    auto_https off\n}\n\n")
	}

	if acmeEmail != "" {
		fmt.Fprintf(&b, "{\n    email %s\n}\n\n", acmeEmail)
	}

	enabled := make([]*db.Site, 0, len(sites))
	for _, s := range sites {
		if s.Enabled {
			enabled = append(enabled, s)
		}
	}
	sort.Slice(enabled, func(i, j int) bool {
		return enabled[i].Domain < enabled[j].Domain
	})

	for _, s := range enabled {
		// Loopback sites MUST listen on :80 — force the http:// scheme
		// regardless of what the user picked, since Caddy can never serve
		// them over HTTPS with a real cert.
		scheme := ""
		if s.Scheme == "http" || IsLoopbackDomain(s.Domain) {
			// Force the listener to bind :80 (without http:// prefix, Caddy
			// only listens on :443 even with auto_https off).
			scheme = "http://"
		}
		fmt.Fprintf(&b, "%s%s {\n", scheme, s.Domain)
		fmt.Fprintf(&b, "    reverse_proxy %s\n", s.Upstream)
		b.WriteString("}\n\n")
	}

	return b.String()
}

// autoHTTPSEnabled returns true when NANOKU_CADDY_AUTO_HTTPS is unset or
// set to a truthy value. Default is true (production-friendly: HTTPS by default).
// Set NANOKU_CADDY_AUTO_HTTPS=false to disable globally (e.g. local dev).
func autoHTTPSEnabled() bool {
	v := strings.ToLower(strings.TrimSpace(os.Getenv("NANOKU_CADDY_AUTO_HTTPS")))
	if v == "" {
		return true
	}
	return v == "1" || v == "true" || v == "yes"
}
