package caddy

import (
	"strings"
	"testing"
)

func TestRender_EmptySites(t *testing.T) {
	out := Render(nil, "")
	if !strings.Contains(out, "Auto-generated by Nanoku") {
		t.Errorf("missing header comment, got:\n%s", out)
	}
	if strings.Contains(out, "auto_https off") {
		t.Errorf("default should keep auto-HTTPS on, got:\n%s", out)
	}
}

func TestRender_DisabledSitesAreSkipped(t *testing.T) {
	sites := []Site{
		{Domain: "a.example.com", Upstream: "app:3000", Scheme: "https", Enabled: true},
		{Domain: "b.example.com", Upstream: "app:3001", Scheme: "https", Enabled: false},
	}
	out := Render(sites, "")
	if !strings.Contains(out, "a.example.com") {
		t.Errorf("enabled site missing:\n%s", out)
	}
	if strings.Contains(out, "b.example.com") {
		t.Errorf("disabled site must be skipped:\n%s", out)
	}
}

func TestRender_SortsByDomain(t *testing.T) {
	sites := []Site{
		{Domain: "zeta.example.com", Upstream: "a:1", Scheme: "https", Enabled: true},
		{Domain: "alpha.example.com", Upstream: "a:2", Scheme: "https", Enabled: true},
		{Domain: "mike.example.com", Upstream: "a:3", Scheme: "https", Enabled: true},
	}
	out := Render(sites, "")
	zi := strings.Index(out, "zeta")
	ai := strings.Index(out, "alpha")
	mi := strings.Index(out, "mike")
	if !(ai < mi && mi < zi) {
		t.Errorf("expected alpha < mike < zeta, got indexes %d/%d/%d in:\n%s", ai, mi, zi, out)
	}
}

func TestRender_ACMEEmail(t *testing.T) {
	out := Render(nil, "ops@example.com")
	if !strings.Contains(out, "email ops@example.com") {
		t.Errorf("acme email not rendered:\n%s", out)
	}
}

func TestRender_HTTPSSiteUsesDefaultHTTPS(t *testing.T) {
	out := Render([]Site{{Domain: "x.example.com", Upstream: "app:80", Scheme: "https", Enabled: true}}, "")
	if strings.Contains(out, "auto_https off") {
		t.Errorf("auto_https should NOT be off by default:\n%s", out)
	}
	if strings.Contains(out, "http://x.example.com") {
		t.Errorf("https site should not force http:// scheme:\n%s", out)
	}
	if !strings.Contains(out, "reverse_proxy app:80") {
		t.Errorf("upstream missing:\n%s", out)
	}
}

func TestRender_HTTPSiteForcesHTTPScheme(t *testing.T) {
	out := Render([]Site{{Domain: "x.example.com", Upstream: "app:80", Scheme: "http", Enabled: true}}, "")
	if !strings.Contains(out, "http://x.example.com") {
		t.Errorf("http site should force http:// scheme:\n%s", out)
	}
	if !strings.Contains(out, "reverse_proxy app:80") {
		t.Errorf("upstream missing:\n%s", out)
	}
}

func TestRender_AutoHTTPSGloballyOff(t *testing.T) {
	t.Setenv("NANOKU_CADDY_AUTO_HTTPS", "false")
	out := Render([]Site{
		{Domain: "a.example.com", Upstream: "app:1", Scheme: "https", Enabled: true},
		{Domain: "b.example.com", Upstream: "app:2", Scheme: "http", Enabled: true},
	}, "")
	if !strings.Contains(out, "auto_https off") {
		t.Errorf("env=false should emit global auto_https off block:\n%s", out)
	}
	// https site no longer needs http:// prefix when global auto_https is off
	if strings.Contains(out, "http://a.example.com") {
		t.Errorf("https site under global auto_https off should not force http://:\n%s", out)
	}
	// http site still gets http:// prefix to ensure :80 binding
	if !strings.Contains(out, "http://b.example.com") {
		t.Errorf("http site should keep http:// scheme even under global off:\n%s", out)
	}
}

func TestRender_LoopbackSiteForcesHTTP(t *testing.T) {
	out := Render([]Site{
		{Domain: "localhost", Upstream: "app:3000", Scheme: "https", Enabled: true},
	}, "")
	if !strings.Contains(out, "auto_https off") {
		t.Errorf("loopback site should force global auto_https off:\n%s", out)
	}
	if !strings.Contains(out, "http://localhost {") {
		t.Errorf("loopback site should render with http:// scheme regardless of Scheme field:\n%s", out)
	}
	if !strings.Contains(out, "reverse_proxy app:3000") {
		t.Errorf("upstream missing:\n%s", out)
	}
}

func TestRender_LoopbackIPLiteralForcesHTTP(t *testing.T) {
	out := Render([]Site{
		{Domain: "127.0.0.1", Upstream: "app:3000", Scheme: "https", Enabled: true},
		{Domain: "::1", Upstream: "app:3000", Scheme: "https", Enabled: true},
	}, "")
	if !strings.Contains(out, "http://127.0.0.1") {
		t.Errorf("127.0.0.1 should render as http://:\n%s", out)
	}
	if !strings.Contains(out, "http://::1") {
		t.Errorf("::1 should render as http://:\n%s", out)
	}
}

func TestRender_LoopbackSubdomainForcesHTTP(t *testing.T) {
	out := Render([]Site{
		{Domain: "app.localhost", Upstream: "app:3000", Scheme: "https", Enabled: true},
	}, "")
	if !strings.Contains(out, "http://app.localhost") {
		t.Errorf("*.localhost should render as http://:\n%s", out)
	}
}

func TestRender_LoopbackSiteMixedWithPublicKeepsGlobalOff(t *testing.T) {
	// If at least one site is loopback, global auto_https must be off.
	// Public sites under that same file will then not auto-upgrade to
	// HTTPS — users mixing both should put them on separate Nanoku
	// instances or stick to one scheme. We only assert the rendering
	// consequence here, not the deployment guidance.
	out := Render([]Site{
		{Domain: "localhost", Upstream: "a:1", Scheme: "http", Enabled: true},
		{Domain: "app.example.com", Upstream: "b:2", Scheme: "https", Enabled: true},
	}, "")
	if !strings.Contains(out, "auto_https off") {
		t.Errorf("any loopback site should still flip global auto_https off:\n%s", out)
	}
}

func TestRender_DisabledLoopbackSiteDoesNotForceGlobalOff(t *testing.T) {
	// A loopback site that's disabled should not pull auto_https down,
	// otherwise the user gets a confusing global state change.
	out := Render([]Site{
		{Domain: "localhost", Upstream: "a:1", Scheme: "http", Enabled: false},
		{Domain: "app.example.com", Upstream: "b:2", Scheme: "https", Enabled: true},
	}, "")
	if strings.Contains(out, "auto_https off") {
		t.Errorf("disabled loopback site should not flip global auto_https off:\n%s", out)
	}
}

func TestIsLoopbackDomain(t *testing.T) {
	cases := []struct {
		domain string
		want   bool
	}{
		{"localhost", true},
		{"LOCALHOST", true},
		{"Localhost", true},
		{"app.localhost", true},
		{"a.b.localhost", true},
		{"127.0.0.1", true},
		{"127.1.2.3", true}, // whole 127.0.0.0/8
		{"::1", true},
		{"app.example.com", false},
		{"example.com", false},
		{"myapp.local", false}, // mDNS, not loopback
		{"", false},
		{"  localhost  ", true}, // trimmed
	}
	for _, tc := range cases {
		if got := IsLoopbackDomain(tc.domain); got != tc.want {
			t.Errorf("IsLoopbackDomain(%q) = %v, want %v", tc.domain, got, tc.want)
		}
	}
}
