package caddy

import (
	"fmt"
	"os"
	"sort"
	"strings"

	"github.com/isaced/nanoku/internal/db"
)

func Render(sites []*db.Site, acmeEmail string) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by Nanoku. Do not edit.\n")
	b.WriteString("# Regenerated on every Site change.\n\n")

	// Global options. For local development, drop HTTPS entirely and serve HTTP
// only on :80 — simpler than chasing certs for .local domains.
// For production, set NANOKU_CADDY_AUTO_HTTPS=true to keep default behavior.
	if !autoHTTPSEnabled() {
		b.WriteString("{\n    auto_https off\n}\n\n")
	}

	if acmeEmail != "" {
		fmt.Fprintf(&b, "{\n    email %s\n}\n\n", acmeEmail)
	}

	enabled := make([]*db.Site, 0, len(sites))
	for _, s := range sites {
		if s.Enabled {
			enabled = append(enabled, s)
		}
	}
	sort.Slice(enabled, func(i, j int) bool {
		return enabled[i].Domain < enabled[j].Domain
	})

	for _, s := range enabled {
		scheme := ""
		if !autoHTTPSEnabled() {
			// Force the listener to bind :80 (without http:// prefix, Caddy
			// only listens on :443 even with auto_https off).
			scheme = "http://"
		}
		fmt.Fprintf(&b, "%s%s {\n", scheme, s.Domain)
		fmt.Fprintf(&b, "    reverse_proxy %s\n", s.Upstream)
		b.WriteString("}\n\n")
	}

	return b.String()
}

// autoHTTPSEnabled returns true when NANOKU_CADDY_AUTO_HTTPS=true is set.
// Default is false (local-dev friendly).
func autoHTTPSEnabled() bool {
	v := strings.ToLower(strings.TrimSpace(os.Getenv("NANOKU_CADDY_AUTO_HTTPS")))
	return v == "1" || v == "true" || v == "yes"
}