// Code generated by ent, DO NOT EDIT.

package deploy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldUpdatedAt, v))
}

// CommitSha applies equality check predicate on the "commit_sha" field. It's identical to CommitShaEQ.
func CommitSha(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCommitSha, v))
}

// CommitMessage applies equality check predicate on the "commit_message" field. It's identical to CommitMessageEQ.
func CommitMessage(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCommitMessage, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldError, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldFinishedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldUpdatedAt, v))
}

// CommitShaEQ applies the EQ predicate on the "commit_sha" field.
func CommitShaEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCommitSha, v))
}

// CommitShaNEQ applies the NEQ predicate on the "commit_sha" field.
func CommitShaNEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldCommitSha, v))
}

// CommitShaIn applies the In predicate on the "commit_sha" field.
func CommitShaIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldCommitSha, vs...))
}

// CommitShaNotIn applies the NotIn predicate on the "commit_sha" field.
func CommitShaNotIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldCommitSha, vs...))
}

// CommitShaGT applies the GT predicate on the "commit_sha" field.
func CommitShaGT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldCommitSha, v))
}

// CommitShaGTE applies the GTE predicate on the "commit_sha" field.
func CommitShaGTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldCommitSha, v))
}

// CommitShaLT applies the LT predicate on the "commit_sha" field.
func CommitShaLT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldCommitSha, v))
}

// CommitShaLTE applies the LTE predicate on the "commit_sha" field.
func CommitShaLTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldCommitSha, v))
}

// CommitShaContains applies the Contains predicate on the "commit_sha" field.
func CommitShaContains(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContains(FieldCommitSha, v))
}

// CommitShaHasPrefix applies the HasPrefix predicate on the "commit_sha" field.
func CommitShaHasPrefix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasPrefix(FieldCommitSha, v))
}

// CommitShaHasSuffix applies the HasSuffix predicate on the "commit_sha" field.
func CommitShaHasSuffix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasSuffix(FieldCommitSha, v))
}

// CommitShaIsNil applies the IsNil predicate on the "commit_sha" field.
func CommitShaIsNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldIsNull(FieldCommitSha))
}

// CommitShaNotNil applies the NotNil predicate on the "commit_sha" field.
func CommitShaNotNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldNotNull(FieldCommitSha))
}

// CommitShaEqualFold applies the EqualFold predicate on the "commit_sha" field.
func CommitShaEqualFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEqualFold(FieldCommitSha, v))
}

// CommitShaContainsFold applies the ContainsFold predicate on the "commit_sha" field.
func CommitShaContainsFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContainsFold(FieldCommitSha, v))
}

// CommitMessageEQ applies the EQ predicate on the "commit_message" field.
func CommitMessageEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldCommitMessage, v))
}

// CommitMessageNEQ applies the NEQ predicate on the "commit_message" field.
func CommitMessageNEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldCommitMessage, v))
}

// CommitMessageIn applies the In predicate on the "commit_message" field.
func CommitMessageIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldCommitMessage, vs...))
}

// CommitMessageNotIn applies the NotIn predicate on the "commit_message" field.
func CommitMessageNotIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldCommitMessage, vs...))
}

// CommitMessageGT applies the GT predicate on the "commit_message" field.
func CommitMessageGT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldCommitMessage, v))
}

// CommitMessageGTE applies the GTE predicate on the "commit_message" field.
func CommitMessageGTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldCommitMessage, v))
}

// CommitMessageLT applies the LT predicate on the "commit_message" field.
func CommitMessageLT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldCommitMessage, v))
}

// CommitMessageLTE applies the LTE predicate on the "commit_message" field.
func CommitMessageLTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldCommitMessage, v))
}

// CommitMessageContains applies the Contains predicate on the "commit_message" field.
func CommitMessageContains(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContains(FieldCommitMessage, v))
}

// CommitMessageHasPrefix applies the HasPrefix predicate on the "commit_message" field.
func CommitMessageHasPrefix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasPrefix(FieldCommitMessage, v))
}

// CommitMessageHasSuffix applies the HasSuffix predicate on the "commit_message" field.
func CommitMessageHasSuffix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasSuffix(FieldCommitMessage, v))
}

// CommitMessageIsNil applies the IsNil predicate on the "commit_message" field.
func CommitMessageIsNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldIsNull(FieldCommitMessage))
}

// CommitMessageNotNil applies the NotNil predicate on the "commit_message" field.
func CommitMessageNotNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldNotNull(FieldCommitMessage))
}

// CommitMessageEqualFold applies the EqualFold predicate on the "commit_message" field.
func CommitMessageEqualFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEqualFold(FieldCommitMessage, v))
}

// CommitMessageContainsFold applies the ContainsFold predicate on the "commit_message" field.
func CommitMessageContainsFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContainsFold(FieldCommitMessage, v))
}

// TriggerEQ applies the EQ predicate on the "trigger" field.
func TriggerEQ(v Trigger) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldTrigger, v))
}

// TriggerNEQ applies the NEQ predicate on the "trigger" field.
func TriggerNEQ(v Trigger) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldTrigger, v))
}

// TriggerIn applies the In predicate on the "trigger" field.
func TriggerIn(vs ...Trigger) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldTrigger, vs...))
}

// TriggerNotIn applies the NotIn predicate on the "trigger" field.
func TriggerNotIn(vs ...Trigger) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldTrigger, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldStatus, vs...))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.Deploy {
	return predicate.Deploy(sql.FieldContainsFold(FieldError, v))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldNotNull(FieldStartedAt))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.Deploy {
	return predicate.Deploy(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.Deploy {
	return predicate.Deploy(sql.FieldNotNull(FieldFinishedAt))
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.Deploy {
	return predicate.Deploy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.App) predicate.Deploy {
	return predicate.Deploy(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasContainer applies the HasEdge predicate on the "container" edge.
func HasContainer() predicate.Deploy {
	return predicate.Deploy(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, ContainerTable, ContainerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasContainerWith applies the HasEdge predicate on the "container" edge with a given conditions (other predicates).
func HasContainerWith(preds ...predicate.Container) predicate.Deploy {
	return predicate.Deploy(func(s *sql.Selector) {
		step := newContainerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Deploy) predicate.Deploy {
	return predicate.Deploy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Deploy) predicate.Deploy {
	return predicate.Deploy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Deploy) predicate.Deploy {
	return predicate.Deploy(sql.NotPredicates(p))
}
