// Code generated by ent, DO NOT EDIT.

package container

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldUpdatedAt, v))
}

// DockerID applies equality check predicate on the "docker_id" field. It's identical to DockerIDEQ.
func DockerID(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldDockerID, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldName, v))
}

// Image applies equality check predicate on the "image" field. It's identical to ImageEQ.
func Image(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldImage, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldStartedAt, v))
}

// StoppedAt applies equality check predicate on the "stopped_at" field. It's identical to StoppedAtEQ.
func StoppedAt(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldStoppedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldUpdatedAt, v))
}

// DockerIDEQ applies the EQ predicate on the "docker_id" field.
func DockerIDEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldDockerID, v))
}

// DockerIDNEQ applies the NEQ predicate on the "docker_id" field.
func DockerIDNEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldDockerID, v))
}

// DockerIDIn applies the In predicate on the "docker_id" field.
func DockerIDIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldDockerID, vs...))
}

// DockerIDNotIn applies the NotIn predicate on the "docker_id" field.
func DockerIDNotIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldDockerID, vs...))
}

// DockerIDGT applies the GT predicate on the "docker_id" field.
func DockerIDGT(v string) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldDockerID, v))
}

// DockerIDGTE applies the GTE predicate on the "docker_id" field.
func DockerIDGTE(v string) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldDockerID, v))
}

// DockerIDLT applies the LT predicate on the "docker_id" field.
func DockerIDLT(v string) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldDockerID, v))
}

// DockerIDLTE applies the LTE predicate on the "docker_id" field.
func DockerIDLTE(v string) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldDockerID, v))
}

// DockerIDContains applies the Contains predicate on the "docker_id" field.
func DockerIDContains(v string) predicate.Container {
	return predicate.Container(sql.FieldContains(FieldDockerID, v))
}

// DockerIDHasPrefix applies the HasPrefix predicate on the "docker_id" field.
func DockerIDHasPrefix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasPrefix(FieldDockerID, v))
}

// DockerIDHasSuffix applies the HasSuffix predicate on the "docker_id" field.
func DockerIDHasSuffix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasSuffix(FieldDockerID, v))
}

// DockerIDEqualFold applies the EqualFold predicate on the "docker_id" field.
func DockerIDEqualFold(v string) predicate.Container {
	return predicate.Container(sql.FieldEqualFold(FieldDockerID, v))
}

// DockerIDContainsFold applies the ContainsFold predicate on the "docker_id" field.
func DockerIDContainsFold(v string) predicate.Container {
	return predicate.Container(sql.FieldContainsFold(FieldDockerID, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Container {
	return predicate.Container(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Container {
	return predicate.Container(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Container {
	return predicate.Container(sql.FieldContainsFold(FieldName, v))
}

// ImageEQ applies the EQ predicate on the "image" field.
func ImageEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldImage, v))
}

// ImageNEQ applies the NEQ predicate on the "image" field.
func ImageNEQ(v string) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldImage, v))
}

// ImageIn applies the In predicate on the "image" field.
func ImageIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldImage, vs...))
}

// ImageNotIn applies the NotIn predicate on the "image" field.
func ImageNotIn(vs ...string) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldImage, vs...))
}

// ImageGT applies the GT predicate on the "image" field.
func ImageGT(v string) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldImage, v))
}

// ImageGTE applies the GTE predicate on the "image" field.
func ImageGTE(v string) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldImage, v))
}

// ImageLT applies the LT predicate on the "image" field.
func ImageLT(v string) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldImage, v))
}

// ImageLTE applies the LTE predicate on the "image" field.
func ImageLTE(v string) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldImage, v))
}

// ImageContains applies the Contains predicate on the "image" field.
func ImageContains(v string) predicate.Container {
	return predicate.Container(sql.FieldContains(FieldImage, v))
}

// ImageHasPrefix applies the HasPrefix predicate on the "image" field.
func ImageHasPrefix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasPrefix(FieldImage, v))
}

// ImageHasSuffix applies the HasSuffix predicate on the "image" field.
func ImageHasSuffix(v string) predicate.Container {
	return predicate.Container(sql.FieldHasSuffix(FieldImage, v))
}

// ImageEqualFold applies the EqualFold predicate on the "image" field.
func ImageEqualFold(v string) predicate.Container {
	return predicate.Container(sql.FieldEqualFold(FieldImage, v))
}

// ImageContainsFold applies the ContainsFold predicate on the "image" field.
func ImageContainsFold(v string) predicate.Container {
	return predicate.Container(sql.FieldContainsFold(FieldImage, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldStatus, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldStartedAt, v))
}

// StartedAtIsNil applies the IsNil predicate on the "started_at" field.
func StartedAtIsNil() predicate.Container {
	return predicate.Container(sql.FieldIsNull(FieldStartedAt))
}

// StartedAtNotNil applies the NotNil predicate on the "started_at" field.
func StartedAtNotNil() predicate.Container {
	return predicate.Container(sql.FieldNotNull(FieldStartedAt))
}

// StoppedAtEQ applies the EQ predicate on the "stopped_at" field.
func StoppedAtEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldEQ(FieldStoppedAt, v))
}

// StoppedAtNEQ applies the NEQ predicate on the "stopped_at" field.
func StoppedAtNEQ(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldNEQ(FieldStoppedAt, v))
}

// StoppedAtIn applies the In predicate on the "stopped_at" field.
func StoppedAtIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldIn(FieldStoppedAt, vs...))
}

// StoppedAtNotIn applies the NotIn predicate on the "stopped_at" field.
func StoppedAtNotIn(vs ...time.Time) predicate.Container {
	return predicate.Container(sql.FieldNotIn(FieldStoppedAt, vs...))
}

// StoppedAtGT applies the GT predicate on the "stopped_at" field.
func StoppedAtGT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGT(FieldStoppedAt, v))
}

// StoppedAtGTE applies the GTE predicate on the "stopped_at" field.
func StoppedAtGTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldGTE(FieldStoppedAt, v))
}

// StoppedAtLT applies the LT predicate on the "stopped_at" field.
func StoppedAtLT(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLT(FieldStoppedAt, v))
}

// StoppedAtLTE applies the LTE predicate on the "stopped_at" field.
func StoppedAtLTE(v time.Time) predicate.Container {
	return predicate.Container(sql.FieldLTE(FieldStoppedAt, v))
}

// StoppedAtIsNil applies the IsNil predicate on the "stopped_at" field.
func StoppedAtIsNil() predicate.Container {
	return predicate.Container(sql.FieldIsNull(FieldStoppedAt))
}

// StoppedAtNotNil applies the NotNil predicate on the "stopped_at" field.
func StoppedAtNotNil() predicate.Container {
	return predicate.Container(sql.FieldNotNull(FieldStoppedAt))
}

// HasApp applies the HasEdge predicate on the "app" edge.
func HasApp() predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, AppTable, AppColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAppWith applies the HasEdge predicate on the "app" edge with a given conditions (other predicates).
func HasAppWith(preds ...predicate.App) predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := newAppStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasDeploy applies the HasEdge predicate on the "deploy" edge.
func HasDeploy() predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, DeployTable, DeployColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasDeployWith applies the HasEdge predicate on the "deploy" edge with a given conditions (other predicates).
func HasDeployWith(preds ...predicate.Deploy) predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := newDeployStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasCurrentFor applies the HasEdge predicate on the "current_for" edge.
func HasCurrentFor() predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, CurrentForTable, CurrentForColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCurrentForWith applies the HasEdge predicate on the "current_for" edge with a given conditions (other predicates).
func HasCurrentForWith(preds ...predicate.App) predicate.Container {
	return predicate.Container(func(s *sql.Selector) {
		step := newCurrentForStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Container) predicate.Container {
	return predicate.Container(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Container) predicate.Container {
	return predicate.Container(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Container) predicate.Container {
	return predicate.Container(sql.NotPredicates(p))
}
