// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "repo_url", Type: field.TypeString, Nullable: true},
		{Name: "branch", Type: field.TypeString, Default: "main"},
		{Name: "deploy_method", Type: field.TypeString, Default: "docker"},
		{Name: "compose_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "compose_path", Type: field.TypeString, Nullable: true},
		{Name: "registry_url", Type: field.TypeString, Nullable: true},
		{Name: "registry_username", Type: field.TypeString, Nullable: true},
		{Name: "registry_password", Type: field.TypeString, Nullable: true},
		{Name: "image_repo", Type: field.TypeString, Nullable: true},
		{Name: "webhook_secret", Type: field.TypeString, Nullable: true},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
	}
	// ContainersColumns holds the columns for the "containers" table.
	ContainersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "docker_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"created", "running", "paused", "restarting", "removing", "exited", "dead"}},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "stopped_at", Type: field.TypeTime, Nullable: true},
		{Name: "app_containers", Type: field.TypeInt, Nullable: true},
		{Name: "app_current_container", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "deploy_container", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ContainersTable holds the schema information for the "containers" table.
	ContainersTable = &schema.Table{
		Name:       "containers",
		Columns:    ContainersColumns,
		PrimaryKey: []*schema.Column{ContainersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "containers_apps_containers",
				Columns:    []*schema.Column{ContainersColumns[9]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "containers_apps_current_container",
				Columns:    []*schema.Column{ContainersColumns[10]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "containers_deploys_container",
				Columns:    []*schema.Column{ContainersColumns[11]},
				RefColumns: []*schema.Column{DeploysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "container_status",
				Unique:  false,
				Columns: []*schema.Column{ContainersColumns[6]},
			},
		},
	}
	// DeploysColumns holds the columns for the "deploys" table.
	DeploysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "commit_sha", Type: field.TypeString, Nullable: true},
		{Name: "commit_message", Type: field.TypeString, Nullable: true},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"manual", "webhook"}, Default: "manual"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "success", "failed", "rolled_back"}, Default: "pending"},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "app_deploys", Type: field.TypeInt, Nullable: true},
	}
	// DeploysTable holds the schema information for the "deploys" table.
	DeploysTable = &schema.Table{
		Name:       "deploys",
		Columns:    DeploysColumns,
		PrimaryKey: []*schema.Column{DeploysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deploys_apps_deploys",
				Columns:    []*schema.Column{DeploysColumns[10]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "deploy_status",
				Unique:  false,
				Columns: []*schema.Column{DeploysColumns[6]},
			},
			{
				Name:    "deploy_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeploysColumns[1]},
			},
		},
	}
	// EnvVarsColumns holds the columns for the "env_vars" table.
	EnvVarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Size: 255},
		{Name: "value", Type: field.TypeString},
		{Name: "app_env_vars", Type: field.TypeInt, Nullable: true},
	}
	// EnvVarsTable holds the schema information for the "env_vars" table.
	EnvVarsTable = &schema.Table{
		Name:       "env_vars",
		Columns:    EnvVarsColumns,
		PrimaryKey: []*schema.Column{EnvVarsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "env_vars_apps_env_vars",
				Columns:    []*schema.Column{EnvVarsColumns[5]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "envvar_key_app_env_vars",
				Unique:  true,
				Columns: []*schema.Column{EnvVarsColumns[3], EnvVarsColumns[5]},
			},
		},
	}
	// SitesColumns holds the columns for the "sites" table.
	SitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "upstream", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "app_sites", Type: field.TypeInt, Nullable: true},
	}
	// SitesTable holds the schema information for the "sites" table.
	SitesTable = &schema.Table{
		Name:       "sites",
		Columns:    SitesColumns,
		PrimaryKey: []*schema.Column{SitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sites_apps_sites",
				Columns:    []*schema.Column{SitesColumns[6]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "site_enabled",
				Unique:  false,
				Columns: []*schema.Column{SitesColumns[5]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		ContainersTable,
		DeploysTable,
		EnvVarsTable,
		SitesTable,
	}
)

func init() {
	ContainersTable.ForeignKeys[0].RefTable = AppsTable
	ContainersTable.ForeignKeys[1].RefTable = AppsTable
	ContainersTable.ForeignKeys[2].RefTable = DeploysTable
	DeploysTable.ForeignKeys[0].RefTable = AppsTable
	EnvVarsTable.ForeignKeys[0].RefTable = AppsTable
	SitesTable.ForeignKeys[0].RefTable = AppsTable
}
