// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AppsColumns holds the columns for the "apps" table.
	AppsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "port", Type: field.TypeInt, Nullable: true},
		{Name: "deploy_method", Type: field.TypeString, Default: "docker"},
		{Name: "compose_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
		{Name: "compose_path", Type: field.TypeString, Nullable: true},
		{Name: "registry_url", Type: field.TypeString, Nullable: true},
		{Name: "registry_username", Type: field.TypeString, Nullable: true},
		{Name: "registry_password", Type: field.TypeString, Nullable: true},
		{Name: "trigger_token", Type: field.TypeString, Nullable: true},
		{Name: "delete_volumes_on_remove", Type: field.TypeBool, Default: false},
	}
	// AppsTable holds the schema information for the "apps" table.
	AppsTable = &schema.Table{
		Name:       "apps",
		Columns:    AppsColumns,
		PrimaryKey: []*schema.Column{AppsColumns[0]},
	}
	// ContainersColumns holds the columns for the "containers" table.
	ContainersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "docker_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString, Unique: true},
		{Name: "image", Type: field.TypeString},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"created", "running", "paused", "restarting", "removing", "exited", "dead", "retired"}},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "stopped_at", Type: field.TypeTime, Nullable: true},
		{Name: "app_containers", Type: field.TypeInt, Nullable: true},
		{Name: "app_current_container", Type: field.TypeInt, Unique: true, Nullable: true},
		{Name: "deploy_container", Type: field.TypeInt, Unique: true, Nullable: true},
	}
	// ContainersTable holds the schema information for the "containers" table.
	ContainersTable = &schema.Table{
		Name:       "containers",
		Columns:    ContainersColumns,
		PrimaryKey: []*schema.Column{ContainersColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "containers_apps_containers",
				Columns:    []*schema.Column{ContainersColumns[9]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "containers_apps_current_container",
				Columns:    []*schema.Column{ContainersColumns[10]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
			{
				Symbol:     "containers_deploys_container",
				Columns:    []*schema.Column{ContainersColumns[11]},
				RefColumns: []*schema.Column{DeploysColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "container_status",
				Unique:  false,
				Columns: []*schema.Column{ContainersColumns[6]},
			},
		},
	}
	// DeploysColumns holds the columns for the "deploys" table.
	DeploysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "commit_sha", Type: field.TypeString, Nullable: true},
		{Name: "commit_message", Type: field.TypeString, Nullable: true},
		{Name: "trigger", Type: field.TypeEnum, Enums: []string{"manual", "trigger", "rollback"}, Default: "manual"},
		{Name: "status", Type: field.TypeEnum, Enums: []string{"pending", "running", "success", "failed", "rolled_back"}, Default: "pending"},
		{Name: "error", Type: field.TypeString, Nullable: true},
		{Name: "started_at", Type: field.TypeTime, Nullable: true},
		{Name: "finished_at", Type: field.TypeTime, Nullable: true},
		{Name: "image", Type: field.TypeString, Nullable: true},
		{Name: "app_deploys", Type: field.TypeInt, Nullable: true},
	}
	// DeploysTable holds the schema information for the "deploys" table.
	DeploysTable = &schema.Table{
		Name:       "deploys",
		Columns:    DeploysColumns,
		PrimaryKey: []*schema.Column{DeploysColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "deploys_apps_deploys",
				Columns:    []*schema.Column{DeploysColumns[11]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "deploy_status",
				Unique:  false,
				Columns: []*schema.Column{DeploysColumns[6]},
			},
			{
				Name:    "deploy_created_at",
				Unique:  false,
				Columns: []*schema.Column{DeploysColumns[1]},
			},
		},
	}
	// EnvVarsColumns holds the columns for the "env_vars" table.
	EnvVarsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString, Size: 255},
		{Name: "value", Type: field.TypeString},
		{Name: "app_env_vars", Type: field.TypeInt, Nullable: true},
	}
	// EnvVarsTable holds the schema information for the "env_vars" table.
	EnvVarsTable = &schema.Table{
		Name:       "env_vars",
		Columns:    EnvVarsColumns,
		PrimaryKey: []*schema.Column{EnvVarsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "env_vars_apps_env_vars",
				Columns:    []*schema.Column{EnvVarsColumns[5]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "envvar_key_app_env_vars",
				Unique:  true,
				Columns: []*schema.Column{EnvVarsColumns[3], EnvVarsColumns[5]},
			},
		},
	}
	// SessionsColumns holds the columns for the "sessions" table.
	SessionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "token_hash", Type: field.TypeString, Unique: true, Size: 64},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "last_seen", Type: field.TypeTime},
		{Name: "user_sessions", Type: field.TypeInt},
	}
	// SessionsTable holds the schema information for the "sessions" table.
	SessionsTable = &schema.Table{
		Name:       "sessions",
		Columns:    SessionsColumns,
		PrimaryKey: []*schema.Column{SessionsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sessions_users_sessions",
				Columns:    []*schema.Column{SessionsColumns[5]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// SitesColumns holds the columns for the "sites" table.
	SitesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "domain", Type: field.TypeString, Unique: true},
		{Name: "upstream", Type: field.TypeString},
		{Name: "enabled", Type: field.TypeBool, Default: true},
		{Name: "scheme", Type: field.TypeEnum, Enums: []string{"http", "https"}, Default: "https"},
		{Name: "app_sites", Type: field.TypeInt, Nullable: true},
	}
	// SitesTable holds the schema information for the "sites" table.
	SitesTable = &schema.Table{
		Name:       "sites",
		Columns:    SitesColumns,
		PrimaryKey: []*schema.Column{SitesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "sites_apps_sites",
				Columns:    []*schema.Column{SitesColumns[7]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "site_enabled",
				Unique:  false,
				Columns: []*schema.Column{SitesColumns[5]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "username", Type: field.TypeString, Unique: true},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "role", Type: field.TypeString, Default: "admin"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// VolumesColumns holds the columns for the "volumes" table.
	VolumesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "type", Type: field.TypeEnum, Enums: []string{"volume", "bind"}},
		{Name: "source", Type: field.TypeString, Nullable: true},
		{Name: "target", Type: field.TypeString},
		{Name: "read_only", Type: field.TypeBool, Default: false},
		{Name: "app_volumes", Type: field.TypeInt, Nullable: true},
	}
	// VolumesTable holds the schema information for the "volumes" table.
	VolumesTable = &schema.Table{
		Name:       "volumes",
		Columns:    VolumesColumns,
		PrimaryKey: []*schema.Column{VolumesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "volumes_apps_volumes",
				Columns:    []*schema.Column{VolumesColumns[7]},
				RefColumns: []*schema.Column{AppsColumns[0]},
				OnDelete:   schema.SetNull,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "volume_target_app_volumes",
				Unique:  true,
				Columns: []*schema.Column{VolumesColumns[5], VolumesColumns[7]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AppsTable,
		ContainersTable,
		DeploysTable,
		EnvVarsTable,
		SessionsTable,
		SitesTable,
		UsersTable,
		VolumesTable,
	}
)

func init() {
	ContainersTable.ForeignKeys[0].RefTable = AppsTable
	ContainersTable.ForeignKeys[1].RefTable = AppsTable
	ContainersTable.ForeignKeys[2].RefTable = DeploysTable
	DeploysTable.ForeignKeys[0].RefTable = AppsTable
	EnvVarsTable.ForeignKeys[0].RefTable = AppsTable
	SessionsTable.ForeignKeys[0].RefTable = UsersTable
	SitesTable.ForeignKeys[0].RefTable = AppsTable
	VolumesTable.ForeignKeys[0].RefTable = AppsTable
}
