// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
)

// App is the model entity for the App schema.
type App struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DNS-1123 label; used as Docker container prefix.
	Name string `json:"name,omitempty"`
	// Docker image, e.g. nginx:1.27.
	Image string `json:"image,omitempty"`
	// Internal port the app listens on.
	Port int `json:"port,omitempty"`
	// Git repo URL for future webhook-driven deploys.
	RepoURL *string `json:"repo_url,omitempty"`
	// Branch holds the value of the "branch" field.
	Branch string `json:"branch,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AppQuery when eager-loading is set.
	Edges        AppEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AppEdges holds the relations/edges for other nodes in the graph.
type AppEdges struct {
	// Sites holds the value of the sites edge.
	Sites []*Site `json:"sites,omitempty"`
	// Containers holds the value of the containers edge.
	Containers []*Container `json:"containers,omitempty"`
	// Deploys holds the value of the deploys edge.
	Deploys []*Deploy `json:"deploys,omitempty"`
	// EnvVars holds the value of the env_vars edge.
	EnvVars []*EnvVar `json:"env_vars,omitempty"`
	// The container currently serving traffic for this app.
	CurrentContainer *Container `json:"current_container,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [5]bool
}

// SitesOrErr returns the Sites value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) SitesOrErr() ([]*Site, error) {
	if e.loadedTypes[0] {
		return e.Sites, nil
	}
	return nil, &NotLoadedError{edge: "sites"}
}

// ContainersOrErr returns the Containers value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) ContainersOrErr() ([]*Container, error) {
	if e.loadedTypes[1] {
		return e.Containers, nil
	}
	return nil, &NotLoadedError{edge: "containers"}
}

// DeploysOrErr returns the Deploys value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) DeploysOrErr() ([]*Deploy, error) {
	if e.loadedTypes[2] {
		return e.Deploys, nil
	}
	return nil, &NotLoadedError{edge: "deploys"}
}

// EnvVarsOrErr returns the EnvVars value or an error if the edge
// was not loaded in eager-loading.
func (e AppEdges) EnvVarsOrErr() ([]*EnvVar, error) {
	if e.loadedTypes[3] {
		return e.EnvVars, nil
	}
	return nil, &NotLoadedError{edge: "env_vars"}
}

// CurrentContainerOrErr returns the CurrentContainer value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AppEdges) CurrentContainerOrErr() (*Container, error) {
	if e.CurrentContainer != nil {
		return e.CurrentContainer, nil
	} else if e.loadedTypes[4] {
		return nil, &NotFoundError{label: container.Label}
	}
	return nil, &NotLoadedError{edge: "current_container"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*App) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case app.FieldID, app.FieldPort:
			values[i] = new(sql.NullInt64)
		case app.FieldName, app.FieldImage, app.FieldRepoURL, app.FieldBranch:
			values[i] = new(sql.NullString)
		case app.FieldCreatedAt, app.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the App fields.
func (_m *App) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case app.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case app.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case app.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case app.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case app.FieldImage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field image", values[i])
			} else if value.Valid {
				_m.Image = value.String
			}
		case app.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case app.FieldRepoURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field repo_url", values[i])
			} else if value.Valid {
				_m.RepoURL = new(string)
				*_m.RepoURL = value.String
			}
		case app.FieldBranch:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field branch", values[i])
			} else if value.Valid {
				_m.Branch = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the App.
// This includes values selected through modifiers, order, etc.
func (_m *App) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySites queries the "sites" edge of the App entity.
func (_m *App) QuerySites() *SiteQuery {
	return NewAppClient(_m.config).QuerySites(_m)
}

// QueryContainers queries the "containers" edge of the App entity.
func (_m *App) QueryContainers() *ContainerQuery {
	return NewAppClient(_m.config).QueryContainers(_m)
}

// QueryDeploys queries the "deploys" edge of the App entity.
func (_m *App) QueryDeploys() *DeployQuery {
	return NewAppClient(_m.config).QueryDeploys(_m)
}

// QueryEnvVars queries the "env_vars" edge of the App entity.
func (_m *App) QueryEnvVars() *EnvVarQuery {
	return NewAppClient(_m.config).QueryEnvVars(_m)
}

// QueryCurrentContainer queries the "current_container" edge of the App entity.
func (_m *App) QueryCurrentContainer() *ContainerQuery {
	return NewAppClient(_m.config).QueryCurrentContainer(_m)
}

// Update returns a builder for updating this App.
// Note that you need to call App.Unwrap() before calling this method if this App
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *App) Update() *AppUpdateOne {
	return NewAppClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the App entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *App) Unwrap() *App {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: App is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *App) String() string {
	var builder strings.Builder
	builder.WriteString("App(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("image=")
	builder.WriteString(_m.Image)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	if v := _m.RepoURL; v != nil {
		builder.WriteString("repo_url=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("branch=")
	builder.WriteString(_m.Branch)
	builder.WriteByte(')')
	return builder.String()
}

// Apps is a parsable slice of App.
type Apps []*App
