// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/envvar"
	"github.com/isaced/nanoku/internal/db/predicate"
	"github.com/isaced/nanoku/internal/db/site"
)

// AppUpdate is the builder for updating App entities.
type AppUpdate struct {
	config
	hooks    []Hook
	mutation *AppMutation
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdate) Where(ps ...predicate.App) *AppUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdate) SetUpdatedAt(v time.Time) *AppUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdate) SetName(v string) *AppUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdate) SetNillableName(v *string) *AppUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *AppUpdate) SetImage(v string) *AppUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *AppUpdate) SetNillableImage(v *string) *AppUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *AppUpdate) ClearImage() *AppUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetPort sets the "port" field.
func (_u *AppUpdate) SetPort(v int) *AppUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *AppUpdate) SetNillablePort(v *int) *AppUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *AppUpdate) AddPort(v int) *AppUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *AppUpdate) ClearPort() *AppUpdate {
	_u.mutation.ClearPort()
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *AppUpdate) SetRepoURL(v string) *AppUpdate {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRepoURL(v *string) *AppUpdate {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// ClearRepoURL clears the value of the "repo_url" field.
func (_u *AppUpdate) ClearRepoURL() *AppUpdate {
	_u.mutation.ClearRepoURL()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *AppUpdate) SetBranch(v string) *AppUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *AppUpdate) SetNillableBranch(v *string) *AppUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetDeployMethod sets the "deploy_method" field.
func (_u *AppUpdate) SetDeployMethod(v string) *AppUpdate {
	_u.mutation.SetDeployMethod(v)
	return _u
}

// SetNillableDeployMethod sets the "deploy_method" field if the given value is not nil.
func (_u *AppUpdate) SetNillableDeployMethod(v *string) *AppUpdate {
	if v != nil {
		_u.SetDeployMethod(*v)
	}
	return _u
}

// SetComposeContent sets the "compose_content" field.
func (_u *AppUpdate) SetComposeContent(v string) *AppUpdate {
	_u.mutation.SetComposeContent(v)
	return _u
}

// SetNillableComposeContent sets the "compose_content" field if the given value is not nil.
func (_u *AppUpdate) SetNillableComposeContent(v *string) *AppUpdate {
	if v != nil {
		_u.SetComposeContent(*v)
	}
	return _u
}

// ClearComposeContent clears the value of the "compose_content" field.
func (_u *AppUpdate) ClearComposeContent() *AppUpdate {
	_u.mutation.ClearComposeContent()
	return _u
}

// SetComposePath sets the "compose_path" field.
func (_u *AppUpdate) SetComposePath(v string) *AppUpdate {
	_u.mutation.SetComposePath(v)
	return _u
}

// SetNillableComposePath sets the "compose_path" field if the given value is not nil.
func (_u *AppUpdate) SetNillableComposePath(v *string) *AppUpdate {
	if v != nil {
		_u.SetComposePath(*v)
	}
	return _u
}

// ClearComposePath clears the value of the "compose_path" field.
func (_u *AppUpdate) ClearComposePath() *AppUpdate {
	_u.mutation.ClearComposePath()
	return _u
}

// SetRegistryURL sets the "registry_url" field.
func (_u *AppUpdate) SetRegistryURL(v string) *AppUpdate {
	_u.mutation.SetRegistryURL(v)
	return _u
}

// SetNillableRegistryURL sets the "registry_url" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRegistryURL(v *string) *AppUpdate {
	if v != nil {
		_u.SetRegistryURL(*v)
	}
	return _u
}

// ClearRegistryURL clears the value of the "registry_url" field.
func (_u *AppUpdate) ClearRegistryURL() *AppUpdate {
	_u.mutation.ClearRegistryURL()
	return _u
}

// SetRegistryUsername sets the "registry_username" field.
func (_u *AppUpdate) SetRegistryUsername(v string) *AppUpdate {
	_u.mutation.SetRegistryUsername(v)
	return _u
}

// SetNillableRegistryUsername sets the "registry_username" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRegistryUsername(v *string) *AppUpdate {
	if v != nil {
		_u.SetRegistryUsername(*v)
	}
	return _u
}

// ClearRegistryUsername clears the value of the "registry_username" field.
func (_u *AppUpdate) ClearRegistryUsername() *AppUpdate {
	_u.mutation.ClearRegistryUsername()
	return _u
}

// SetRegistryPassword sets the "registry_password" field.
func (_u *AppUpdate) SetRegistryPassword(v string) *AppUpdate {
	_u.mutation.SetRegistryPassword(v)
	return _u
}

// SetNillableRegistryPassword sets the "registry_password" field if the given value is not nil.
func (_u *AppUpdate) SetNillableRegistryPassword(v *string) *AppUpdate {
	if v != nil {
		_u.SetRegistryPassword(*v)
	}
	return _u
}

// ClearRegistryPassword clears the value of the "registry_password" field.
func (_u *AppUpdate) ClearRegistryPassword() *AppUpdate {
	_u.mutation.ClearRegistryPassword()
	return _u
}

// AddSiteIDs adds the "sites" edge to the Site entity by IDs.
func (_u *AppUpdate) AddSiteIDs(ids ...int) *AppUpdate {
	_u.mutation.AddSiteIDs(ids...)
	return _u
}

// AddSites adds the "sites" edges to the Site entity.
func (_u *AppUpdate) AddSites(v ...*Site) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSiteIDs(ids...)
}

// AddContainerIDs adds the "containers" edge to the Container entity by IDs.
func (_u *AppUpdate) AddContainerIDs(ids ...int) *AppUpdate {
	_u.mutation.AddContainerIDs(ids...)
	return _u
}

// AddContainers adds the "containers" edges to the Container entity.
func (_u *AppUpdate) AddContainers(v ...*Container) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContainerIDs(ids...)
}

// AddDeployIDs adds the "deploys" edge to the Deploy entity by IDs.
func (_u *AppUpdate) AddDeployIDs(ids ...int) *AppUpdate {
	_u.mutation.AddDeployIDs(ids...)
	return _u
}

// AddDeploys adds the "deploys" edges to the Deploy entity.
func (_u *AppUpdate) AddDeploys(v ...*Deploy) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployIDs(ids...)
}

// AddEnvVarIDs adds the "env_vars" edge to the EnvVar entity by IDs.
func (_u *AppUpdate) AddEnvVarIDs(ids ...int) *AppUpdate {
	_u.mutation.AddEnvVarIDs(ids...)
	return _u
}

// AddEnvVars adds the "env_vars" edges to the EnvVar entity.
func (_u *AppUpdate) AddEnvVars(v ...*EnvVar) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvVarIDs(ids...)
}

// SetCurrentContainerID sets the "current_container" edge to the Container entity by ID.
func (_u *AppUpdate) SetCurrentContainerID(id int) *AppUpdate {
	_u.mutation.SetCurrentContainerID(id)
	return _u
}

// SetNillableCurrentContainerID sets the "current_container" edge to the Container entity by ID if the given value is not nil.
func (_u *AppUpdate) SetNillableCurrentContainerID(id *int) *AppUpdate {
	if id != nil {
		_u = _u.SetCurrentContainerID(*id)
	}
	return _u
}

// SetCurrentContainer sets the "current_container" edge to the Container entity.
func (_u *AppUpdate) SetCurrentContainer(v *Container) *AppUpdate {
	return _u.SetCurrentContainerID(v.ID)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdate) Mutation() *AppMutation {
	return _u.mutation
}

// ClearSites clears all "sites" edges to the Site entity.
func (_u *AppUpdate) ClearSites() *AppUpdate {
	_u.mutation.ClearSites()
	return _u
}

// RemoveSiteIDs removes the "sites" edge to Site entities by IDs.
func (_u *AppUpdate) RemoveSiteIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveSiteIDs(ids...)
	return _u
}

// RemoveSites removes "sites" edges to Site entities.
func (_u *AppUpdate) RemoveSites(v ...*Site) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSiteIDs(ids...)
}

// ClearContainers clears all "containers" edges to the Container entity.
func (_u *AppUpdate) ClearContainers() *AppUpdate {
	_u.mutation.ClearContainers()
	return _u
}

// RemoveContainerIDs removes the "containers" edge to Container entities by IDs.
func (_u *AppUpdate) RemoveContainerIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveContainerIDs(ids...)
	return _u
}

// RemoveContainers removes "containers" edges to Container entities.
func (_u *AppUpdate) RemoveContainers(v ...*Container) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContainerIDs(ids...)
}

// ClearDeploys clears all "deploys" edges to the Deploy entity.
func (_u *AppUpdate) ClearDeploys() *AppUpdate {
	_u.mutation.ClearDeploys()
	return _u
}

// RemoveDeployIDs removes the "deploys" edge to Deploy entities by IDs.
func (_u *AppUpdate) RemoveDeployIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveDeployIDs(ids...)
	return _u
}

// RemoveDeploys removes "deploys" edges to Deploy entities.
func (_u *AppUpdate) RemoveDeploys(v ...*Deploy) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployIDs(ids...)
}

// ClearEnvVars clears all "env_vars" edges to the EnvVar entity.
func (_u *AppUpdate) ClearEnvVars() *AppUpdate {
	_u.mutation.ClearEnvVars()
	return _u
}

// RemoveEnvVarIDs removes the "env_vars" edge to EnvVar entities by IDs.
func (_u *AppUpdate) RemoveEnvVarIDs(ids ...int) *AppUpdate {
	_u.mutation.RemoveEnvVarIDs(ids...)
	return _u
}

// RemoveEnvVars removes "env_vars" edges to EnvVar entities.
func (_u *AppUpdate) RemoveEnvVars(v ...*EnvVar) *AppUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvVarIDs(ids...)
}

// ClearCurrentContainer clears the "current_container" edge to the Container entity.
func (_u *AppUpdate) ClearCurrentContainer() *AppUpdate {
	_u.mutation.ClearCurrentContainer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AppUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AppUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := app.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`db: validator failed for field "App.port": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(app.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(app.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(app.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(app.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(app.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(app.FieldRepoURL, field.TypeString, value)
	}
	if _u.mutation.RepoURLCleared() {
		_spec.ClearField(app.FieldRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(app.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployMethod(); ok {
		_spec.SetField(app.FieldDeployMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ComposeContent(); ok {
		_spec.SetField(app.FieldComposeContent, field.TypeString, value)
	}
	if _u.mutation.ComposeContentCleared() {
		_spec.ClearField(app.FieldComposeContent, field.TypeString)
	}
	if value, ok := _u.mutation.ComposePath(); ok {
		_spec.SetField(app.FieldComposePath, field.TypeString, value)
	}
	if _u.mutation.ComposePathCleared() {
		_spec.ClearField(app.FieldComposePath, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryURL(); ok {
		_spec.SetField(app.FieldRegistryURL, field.TypeString, value)
	}
	if _u.mutation.RegistryURLCleared() {
		_spec.ClearField(app.FieldRegistryURL, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryUsername(); ok {
		_spec.SetField(app.FieldRegistryUsername, field.TypeString, value)
	}
	if _u.mutation.RegistryUsernameCleared() {
		_spec.ClearField(app.FieldRegistryUsername, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryPassword(); ok {
		_spec.SetField(app.FieldRegistryPassword, field.TypeString, value)
	}
	if _u.mutation.RegistryPasswordCleared() {
		_spec.ClearField(app.FieldRegistryPassword, field.TypeString)
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesIDs(); len(nodes) > 0 && !_u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContainersIDs(); len(nodes) > 0 && !_u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeploysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeploysIDs(); len(nodes) > 0 && !_u.mutation.DeploysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvVarsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvVarsIDs(); len(nodes) > 0 && !_u.mutation.EnvVarsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvVarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   app.CurrentContainerTable,
			Columns: []string{app.CurrentContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   app.CurrentContainerTable,
			Columns: []string{app.CurrentContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AppUpdateOne is the builder for updating a single App entity.
type AppUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AppMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AppUpdateOne) SetUpdatedAt(v time.Time) *AppUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AppUpdateOne) SetName(v string) *AppUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableName(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *AppUpdateOne) SetImage(v string) *AppUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableImage(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *AppUpdateOne) ClearImage() *AppUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetPort sets the "port" field.
func (_u *AppUpdateOne) SetPort(v int) *AppUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillablePort(v *int) *AppUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *AppUpdateOne) AddPort(v int) *AppUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// ClearPort clears the value of the "port" field.
func (_u *AppUpdateOne) ClearPort() *AppUpdateOne {
	_u.mutation.ClearPort()
	return _u
}

// SetRepoURL sets the "repo_url" field.
func (_u *AppUpdateOne) SetRepoURL(v string) *AppUpdateOne {
	_u.mutation.SetRepoURL(v)
	return _u
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRepoURL(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetRepoURL(*v)
	}
	return _u
}

// ClearRepoURL clears the value of the "repo_url" field.
func (_u *AppUpdateOne) ClearRepoURL() *AppUpdateOne {
	_u.mutation.ClearRepoURL()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *AppUpdateOne) SetBranch(v string) *AppUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableBranch(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetDeployMethod sets the "deploy_method" field.
func (_u *AppUpdateOne) SetDeployMethod(v string) *AppUpdateOne {
	_u.mutation.SetDeployMethod(v)
	return _u
}

// SetNillableDeployMethod sets the "deploy_method" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableDeployMethod(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetDeployMethod(*v)
	}
	return _u
}

// SetComposeContent sets the "compose_content" field.
func (_u *AppUpdateOne) SetComposeContent(v string) *AppUpdateOne {
	_u.mutation.SetComposeContent(v)
	return _u
}

// SetNillableComposeContent sets the "compose_content" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableComposeContent(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetComposeContent(*v)
	}
	return _u
}

// ClearComposeContent clears the value of the "compose_content" field.
func (_u *AppUpdateOne) ClearComposeContent() *AppUpdateOne {
	_u.mutation.ClearComposeContent()
	return _u
}

// SetComposePath sets the "compose_path" field.
func (_u *AppUpdateOne) SetComposePath(v string) *AppUpdateOne {
	_u.mutation.SetComposePath(v)
	return _u
}

// SetNillableComposePath sets the "compose_path" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableComposePath(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetComposePath(*v)
	}
	return _u
}

// ClearComposePath clears the value of the "compose_path" field.
func (_u *AppUpdateOne) ClearComposePath() *AppUpdateOne {
	_u.mutation.ClearComposePath()
	return _u
}

// SetRegistryURL sets the "registry_url" field.
func (_u *AppUpdateOne) SetRegistryURL(v string) *AppUpdateOne {
	_u.mutation.SetRegistryURL(v)
	return _u
}

// SetNillableRegistryURL sets the "registry_url" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRegistryURL(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetRegistryURL(*v)
	}
	return _u
}

// ClearRegistryURL clears the value of the "registry_url" field.
func (_u *AppUpdateOne) ClearRegistryURL() *AppUpdateOne {
	_u.mutation.ClearRegistryURL()
	return _u
}

// SetRegistryUsername sets the "registry_username" field.
func (_u *AppUpdateOne) SetRegistryUsername(v string) *AppUpdateOne {
	_u.mutation.SetRegistryUsername(v)
	return _u
}

// SetNillableRegistryUsername sets the "registry_username" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRegistryUsername(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetRegistryUsername(*v)
	}
	return _u
}

// ClearRegistryUsername clears the value of the "registry_username" field.
func (_u *AppUpdateOne) ClearRegistryUsername() *AppUpdateOne {
	_u.mutation.ClearRegistryUsername()
	return _u
}

// SetRegistryPassword sets the "registry_password" field.
func (_u *AppUpdateOne) SetRegistryPassword(v string) *AppUpdateOne {
	_u.mutation.SetRegistryPassword(v)
	return _u
}

// SetNillableRegistryPassword sets the "registry_password" field if the given value is not nil.
func (_u *AppUpdateOne) SetNillableRegistryPassword(v *string) *AppUpdateOne {
	if v != nil {
		_u.SetRegistryPassword(*v)
	}
	return _u
}

// ClearRegistryPassword clears the value of the "registry_password" field.
func (_u *AppUpdateOne) ClearRegistryPassword() *AppUpdateOne {
	_u.mutation.ClearRegistryPassword()
	return _u
}

// AddSiteIDs adds the "sites" edge to the Site entity by IDs.
func (_u *AppUpdateOne) AddSiteIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddSiteIDs(ids...)
	return _u
}

// AddSites adds the "sites" edges to the Site entity.
func (_u *AppUpdateOne) AddSites(v ...*Site) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSiteIDs(ids...)
}

// AddContainerIDs adds the "containers" edge to the Container entity by IDs.
func (_u *AppUpdateOne) AddContainerIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddContainerIDs(ids...)
	return _u
}

// AddContainers adds the "containers" edges to the Container entity.
func (_u *AppUpdateOne) AddContainers(v ...*Container) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddContainerIDs(ids...)
}

// AddDeployIDs adds the "deploys" edge to the Deploy entity by IDs.
func (_u *AppUpdateOne) AddDeployIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddDeployIDs(ids...)
	return _u
}

// AddDeploys adds the "deploys" edges to the Deploy entity.
func (_u *AppUpdateOne) AddDeploys(v ...*Deploy) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddDeployIDs(ids...)
}

// AddEnvVarIDs adds the "env_vars" edge to the EnvVar entity by IDs.
func (_u *AppUpdateOne) AddEnvVarIDs(ids ...int) *AppUpdateOne {
	_u.mutation.AddEnvVarIDs(ids...)
	return _u
}

// AddEnvVars adds the "env_vars" edges to the EnvVar entity.
func (_u *AppUpdateOne) AddEnvVars(v ...*EnvVar) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddEnvVarIDs(ids...)
}

// SetCurrentContainerID sets the "current_container" edge to the Container entity by ID.
func (_u *AppUpdateOne) SetCurrentContainerID(id int) *AppUpdateOne {
	_u.mutation.SetCurrentContainerID(id)
	return _u
}

// SetNillableCurrentContainerID sets the "current_container" edge to the Container entity by ID if the given value is not nil.
func (_u *AppUpdateOne) SetNillableCurrentContainerID(id *int) *AppUpdateOne {
	if id != nil {
		_u = _u.SetCurrentContainerID(*id)
	}
	return _u
}

// SetCurrentContainer sets the "current_container" edge to the Container entity.
func (_u *AppUpdateOne) SetCurrentContainer(v *Container) *AppUpdateOne {
	return _u.SetCurrentContainerID(v.ID)
}

// Mutation returns the AppMutation object of the builder.
func (_u *AppUpdateOne) Mutation() *AppMutation {
	return _u.mutation
}

// ClearSites clears all "sites" edges to the Site entity.
func (_u *AppUpdateOne) ClearSites() *AppUpdateOne {
	_u.mutation.ClearSites()
	return _u
}

// RemoveSiteIDs removes the "sites" edge to Site entities by IDs.
func (_u *AppUpdateOne) RemoveSiteIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveSiteIDs(ids...)
	return _u
}

// RemoveSites removes "sites" edges to Site entities.
func (_u *AppUpdateOne) RemoveSites(v ...*Site) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSiteIDs(ids...)
}

// ClearContainers clears all "containers" edges to the Container entity.
func (_u *AppUpdateOne) ClearContainers() *AppUpdateOne {
	_u.mutation.ClearContainers()
	return _u
}

// RemoveContainerIDs removes the "containers" edge to Container entities by IDs.
func (_u *AppUpdateOne) RemoveContainerIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveContainerIDs(ids...)
	return _u
}

// RemoveContainers removes "containers" edges to Container entities.
func (_u *AppUpdateOne) RemoveContainers(v ...*Container) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveContainerIDs(ids...)
}

// ClearDeploys clears all "deploys" edges to the Deploy entity.
func (_u *AppUpdateOne) ClearDeploys() *AppUpdateOne {
	_u.mutation.ClearDeploys()
	return _u
}

// RemoveDeployIDs removes the "deploys" edge to Deploy entities by IDs.
func (_u *AppUpdateOne) RemoveDeployIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveDeployIDs(ids...)
	return _u
}

// RemoveDeploys removes "deploys" edges to Deploy entities.
func (_u *AppUpdateOne) RemoveDeploys(v ...*Deploy) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveDeployIDs(ids...)
}

// ClearEnvVars clears all "env_vars" edges to the EnvVar entity.
func (_u *AppUpdateOne) ClearEnvVars() *AppUpdateOne {
	_u.mutation.ClearEnvVars()
	return _u
}

// RemoveEnvVarIDs removes the "env_vars" edge to EnvVar entities by IDs.
func (_u *AppUpdateOne) RemoveEnvVarIDs(ids ...int) *AppUpdateOne {
	_u.mutation.RemoveEnvVarIDs(ids...)
	return _u
}

// RemoveEnvVars removes "env_vars" edges to EnvVar entities.
func (_u *AppUpdateOne) RemoveEnvVars(v ...*EnvVar) *AppUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveEnvVarIDs(ids...)
}

// ClearCurrentContainer clears the "current_container" edge to the Container entity.
func (_u *AppUpdateOne) ClearCurrentContainer() *AppUpdateOne {
	_u.mutation.ClearCurrentContainer()
	return _u
}

// Where appends a list predicates to the AppUpdate builder.
func (_u *AppUpdateOne) Where(ps ...predicate.App) *AppUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AppUpdateOne) Select(field string, fields ...string) *AppUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated App entity.
func (_u *AppUpdateOne) Save(ctx context.Context) (*App, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AppUpdateOne) SaveX(ctx context.Context) *App {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AppUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AppUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AppUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := app.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AppUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "App.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Port(); ok {
		if err := app.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`db: validator failed for field "App.port": %w`, err)}
		}
	}
	return nil
}

func (_u *AppUpdateOne) sqlSave(ctx context.Context) (_node *App, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "App.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for _, f := range fields {
			if !app.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(app.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(app.FieldImage, field.TypeString)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(app.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(app.FieldPort, field.TypeInt, value)
	}
	if _u.mutation.PortCleared() {
		_spec.ClearField(app.FieldPort, field.TypeInt)
	}
	if value, ok := _u.mutation.RepoURL(); ok {
		_spec.SetField(app.FieldRepoURL, field.TypeString, value)
	}
	if _u.mutation.RepoURLCleared() {
		_spec.ClearField(app.FieldRepoURL, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(app.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.DeployMethod(); ok {
		_spec.SetField(app.FieldDeployMethod, field.TypeString, value)
	}
	if value, ok := _u.mutation.ComposeContent(); ok {
		_spec.SetField(app.FieldComposeContent, field.TypeString, value)
	}
	if _u.mutation.ComposeContentCleared() {
		_spec.ClearField(app.FieldComposeContent, field.TypeString)
	}
	if value, ok := _u.mutation.ComposePath(); ok {
		_spec.SetField(app.FieldComposePath, field.TypeString, value)
	}
	if _u.mutation.ComposePathCleared() {
		_spec.ClearField(app.FieldComposePath, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryURL(); ok {
		_spec.SetField(app.FieldRegistryURL, field.TypeString, value)
	}
	if _u.mutation.RegistryURLCleared() {
		_spec.ClearField(app.FieldRegistryURL, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryUsername(); ok {
		_spec.SetField(app.FieldRegistryUsername, field.TypeString, value)
	}
	if _u.mutation.RegistryUsernameCleared() {
		_spec.ClearField(app.FieldRegistryUsername, field.TypeString)
	}
	if value, ok := _u.mutation.RegistryPassword(); ok {
		_spec.SetField(app.FieldRegistryPassword, field.TypeString, value)
	}
	if _u.mutation.RegistryPasswordCleared() {
		_spec.ClearField(app.FieldRegistryPassword, field.TypeString)
	}
	if _u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSitesIDs(); len(nodes) > 0 && !_u.mutation.SitesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedContainersIDs(); len(nodes) > 0 && !_u.mutation.ContainersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeploysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedDeploysIDs(); len(nodes) > 0 && !_u.mutation.DeploysCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeploysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.EnvVarsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedEnvVarsIDs(); len(nodes) > 0 && !_u.mutation.EnvVarsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.EnvVarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   app.CurrentContainerTable,
			Columns: []string{app.CurrentContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   app.CurrentContainerTable,
			Columns: []string{app.CurrentContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &App{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{app.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
