// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/envvar"
	"github.com/isaced/nanoku/internal/db/site"
)

// AppCreate is the builder for creating a App entity.
type AppCreate struct {
	config
	mutation *AppMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AppCreate) SetCreatedAt(v time.Time) *AppCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableCreatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AppCreate) SetUpdatedAt(v time.Time) *AppCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AppCreate) SetNillableUpdatedAt(v *time.Time) *AppCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *AppCreate) SetName(v string) *AppCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetImage sets the "image" field.
func (_c *AppCreate) SetImage(v string) *AppCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetPort sets the "port" field.
func (_c *AppCreate) SetPort(v int) *AppCreate {
	_c.mutation.SetPort(v)
	return _c
}

// SetRepoURL sets the "repo_url" field.
func (_c *AppCreate) SetRepoURL(v string) *AppCreate {
	_c.mutation.SetRepoURL(v)
	return _c
}

// SetNillableRepoURL sets the "repo_url" field if the given value is not nil.
func (_c *AppCreate) SetNillableRepoURL(v *string) *AppCreate {
	if v != nil {
		_c.SetRepoURL(*v)
	}
	return _c
}

// SetBranch sets the "branch" field.
func (_c *AppCreate) SetBranch(v string) *AppCreate {
	_c.mutation.SetBranch(v)
	return _c
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_c *AppCreate) SetNillableBranch(v *string) *AppCreate {
	if v != nil {
		_c.SetBranch(*v)
	}
	return _c
}

// AddSiteIDs adds the "sites" edge to the Site entity by IDs.
func (_c *AppCreate) AddSiteIDs(ids ...int) *AppCreate {
	_c.mutation.AddSiteIDs(ids...)
	return _c
}

// AddSites adds the "sites" edges to the Site entity.
func (_c *AppCreate) AddSites(v ...*Site) *AppCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSiteIDs(ids...)
}

// AddContainerIDs adds the "containers" edge to the Container entity by IDs.
func (_c *AppCreate) AddContainerIDs(ids ...int) *AppCreate {
	_c.mutation.AddContainerIDs(ids...)
	return _c
}

// AddContainers adds the "containers" edges to the Container entity.
func (_c *AppCreate) AddContainers(v ...*Container) *AppCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddContainerIDs(ids...)
}

// AddDeployIDs adds the "deploys" edge to the Deploy entity by IDs.
func (_c *AppCreate) AddDeployIDs(ids ...int) *AppCreate {
	_c.mutation.AddDeployIDs(ids...)
	return _c
}

// AddDeploys adds the "deploys" edges to the Deploy entity.
func (_c *AppCreate) AddDeploys(v ...*Deploy) *AppCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddDeployIDs(ids...)
}

// AddEnvVarIDs adds the "env_vars" edge to the EnvVar entity by IDs.
func (_c *AppCreate) AddEnvVarIDs(ids ...int) *AppCreate {
	_c.mutation.AddEnvVarIDs(ids...)
	return _c
}

// AddEnvVars adds the "env_vars" edges to the EnvVar entity.
func (_c *AppCreate) AddEnvVars(v ...*EnvVar) *AppCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddEnvVarIDs(ids...)
}

// SetCurrentContainerID sets the "current_container" edge to the Container entity by ID.
func (_c *AppCreate) SetCurrentContainerID(id int) *AppCreate {
	_c.mutation.SetCurrentContainerID(id)
	return _c
}

// SetNillableCurrentContainerID sets the "current_container" edge to the Container entity by ID if the given value is not nil.
func (_c *AppCreate) SetNillableCurrentContainerID(id *int) *AppCreate {
	if id != nil {
		_c = _c.SetCurrentContainerID(*id)
	}
	return _c
}

// SetCurrentContainer sets the "current_container" edge to the Container entity.
func (_c *AppCreate) SetCurrentContainer(v *Container) *AppCreate {
	return _c.SetCurrentContainerID(v.ID)
}

// Mutation returns the AppMutation object of the builder.
func (_c *AppCreate) Mutation() *AppMutation {
	return _c.mutation
}

// Save creates the App in the database.
func (_c *AppCreate) Save(ctx context.Context) (*App, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AppCreate) SaveX(ctx context.Context) *App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AppCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := app.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := app.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Branch(); !ok {
		v := app.DefaultBranch
		_c.mutation.SetBranch(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AppCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "App.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "App.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "App.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := app.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`db: validator failed for field "App.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`db: missing required field "App.image"`)}
	}
	if _, ok := _c.mutation.Port(); !ok {
		return &ValidationError{Name: "port", err: errors.New(`db: missing required field "App.port"`)}
	}
	if v, ok := _c.mutation.Port(); ok {
		if err := app.PortValidator(v); err != nil {
			return &ValidationError{Name: "port", err: fmt.Errorf(`db: validator failed for field "App.port": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Branch(); !ok {
		return &ValidationError{Name: "branch", err: errors.New(`db: missing required field "App.branch"`)}
	}
	return nil
}

func (_c *AppCreate) sqlSave(ctx context.Context) (*App, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AppCreate) createSpec() (*App, *sqlgraph.CreateSpec) {
	var (
		_node = &App{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(app.Table, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(app.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(app.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(app.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(app.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := _c.mutation.Port(); ok {
		_spec.SetField(app.FieldPort, field.TypeInt, value)
		_node.Port = value
	}
	if value, ok := _c.mutation.RepoURL(); ok {
		_spec.SetField(app.FieldRepoURL, field.TypeString, value)
		_node.RepoURL = &value
	}
	if value, ok := _c.mutation.Branch(); ok {
		_spec.SetField(app.FieldBranch, field.TypeString, value)
		_node.Branch = value
	}
	if nodes := _c.mutation.SitesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.SitesTable,
			Columns: []string{app.SitesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContainersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.ContainersTable,
			Columns: []string{app.ContainersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeploysIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.DeploysTable,
			Columns: []string{app.DeploysColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.EnvVarsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   app.EnvVarsTable,
			Columns: []string{app.EnvVarsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrentContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   app.CurrentContainerTable,
			Columns: []string{app.CurrentContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AppCreateBulk is the builder for creating many App entities in bulk.
type AppCreateBulk struct {
	config
	err      error
	builders []*AppCreate
}

// Save creates the App entities in the database.
func (_c *AppCreateBulk) Save(ctx context.Context) ([]*App, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*App, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AppMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AppCreateBulk) SaveX(ctx context.Context) []*App {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AppCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AppCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
