// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/envvar"
	"github.com/isaced/nanoku/internal/db/predicate"
	"github.com/isaced/nanoku/internal/db/site"
	"github.com/isaced/nanoku/internal/db/volume"
)

// AppQuery is the builder for querying App entities.
type AppQuery struct {
	config
	ctx                  *QueryContext
	order                []app.OrderOption
	inters               []Interceptor
	predicates           []predicate.App
	withSites            *SiteQuery
	withContainers       *ContainerQuery
	withDeploys          *DeployQuery
	withEnvVars          *EnvVarQuery
	withVolumes          *VolumeQuery
	withCurrentContainer *ContainerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the AppQuery builder.
func (_q *AppQuery) Where(ps ...predicate.App) *AppQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *AppQuery) Limit(limit int) *AppQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *AppQuery) Offset(offset int) *AppQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *AppQuery) Unique(unique bool) *AppQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *AppQuery) Order(o ...app.OrderOption) *AppQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QuerySites chains the current query on the "sites" edge.
func (_q *AppQuery) QuerySites() *SiteQuery {
	query := (&SiteClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(site.Table, site.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.SitesTable, app.SitesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryContainers chains the current query on the "containers" edge.
func (_q *AppQuery) QueryContainers() *ContainerQuery {
	query := (&ContainerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(container.Table, container.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.ContainersTable, app.ContainersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDeploys chains the current query on the "deploys" edge.
func (_q *AppQuery) QueryDeploys() *DeployQuery {
	query := (&DeployClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(deploy.Table, deploy.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.DeploysTable, app.DeploysColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryEnvVars chains the current query on the "env_vars" edge.
func (_q *AppQuery) QueryEnvVars() *EnvVarQuery {
	query := (&EnvVarClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(envvar.Table, envvar.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.EnvVarsTable, app.EnvVarsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryVolumes chains the current query on the "volumes" edge.
func (_q *AppQuery) QueryVolumes() *VolumeQuery {
	query := (&VolumeClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(volume.Table, volume.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, app.VolumesTable, app.VolumesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryCurrentContainer chains the current query on the "current_container" edge.
func (_q *AppQuery) QueryCurrentContainer() *ContainerQuery {
	query := (&ContainerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(app.Table, app.FieldID, selector),
			sqlgraph.To(container.Table, container.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, false, app.CurrentContainerTable, app.CurrentContainerColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first App entity from the query.
// Returns a *NotFoundError when no App was found.
func (_q *AppQuery) First(ctx context.Context) (*App, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{app.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *AppQuery) FirstX(ctx context.Context) *App {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first App ID from the query.
// Returns a *NotFoundError when no App ID was found.
func (_q *AppQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{app.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *AppQuery) FirstIDX(ctx context.Context) int {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single App entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one App entity is found.
// Returns a *NotFoundError when no App entities are found.
func (_q *AppQuery) Only(ctx context.Context) (*App, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{app.Label}
	default:
		return nil, &NotSingularError{app.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *AppQuery) OnlyX(ctx context.Context) *App {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only App ID in the query.
// Returns a *NotSingularError when more than one App ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *AppQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{app.Label}
	default:
		err = &NotSingularError{app.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *AppQuery) OnlyIDX(ctx context.Context) int {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Apps.
func (_q *AppQuery) All(ctx context.Context) ([]*App, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*App, *AppQuery]()
	return withInterceptors[[]*App](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *AppQuery) AllX(ctx context.Context) []*App {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of App IDs.
func (_q *AppQuery) IDs(ctx context.Context) (ids []int, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(app.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *AppQuery) IDsX(ctx context.Context) []int {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *AppQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*AppQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *AppQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *AppQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("db: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *AppQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the AppQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *AppQuery) Clone() *AppQuery {
	if _q == nil {
		return nil
	}
	return &AppQuery{
		config:               _q.config,
		ctx:                  _q.ctx.Clone(),
		order:                append([]app.OrderOption{}, _q.order...),
		inters:               append([]Interceptor{}, _q.inters...),
		predicates:           append([]predicate.App{}, _q.predicates...),
		withSites:            _q.withSites.Clone(),
		withContainers:       _q.withContainers.Clone(),
		withDeploys:          _q.withDeploys.Clone(),
		withEnvVars:          _q.withEnvVars.Clone(),
		withVolumes:          _q.withVolumes.Clone(),
		withCurrentContainer: _q.withCurrentContainer.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithSites tells the query-builder to eager-load the nodes that are connected to
// the "sites" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithSites(opts ...func(*SiteQuery)) *AppQuery {
	query := (&SiteClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withSites = query
	return _q
}

// WithContainers tells the query-builder to eager-load the nodes that are connected to
// the "containers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithContainers(opts ...func(*ContainerQuery)) *AppQuery {
	query := (&ContainerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withContainers = query
	return _q
}

// WithDeploys tells the query-builder to eager-load the nodes that are connected to
// the "deploys" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithDeploys(opts ...func(*DeployQuery)) *AppQuery {
	query := (&DeployClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDeploys = query
	return _q
}

// WithEnvVars tells the query-builder to eager-load the nodes that are connected to
// the "env_vars" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithEnvVars(opts ...func(*EnvVarQuery)) *AppQuery {
	query := (&EnvVarClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withEnvVars = query
	return _q
}

// WithVolumes tells the query-builder to eager-load the nodes that are connected to
// the "volumes" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithVolumes(opts ...func(*VolumeQuery)) *AppQuery {
	query := (&VolumeClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withVolumes = query
	return _q
}

// WithCurrentContainer tells the query-builder to eager-load the nodes that are connected to
// the "current_container" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *AppQuery) WithCurrentContainer(opts ...func(*ContainerQuery)) *AppQuery {
	query := (&ContainerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withCurrentContainer = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.App.Query().
//		GroupBy(app.FieldCreatedAt).
//		Aggregate(db.Count()).
//		Scan(ctx, &v)
func (_q *AppQuery) GroupBy(field string, fields ...string) *AppGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &AppGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = app.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreatedAt time.Time `json:"created_at,omitempty"`
//	}
//
//	client.App.Query().
//		Select(app.FieldCreatedAt).
//		Scan(ctx, &v)
func (_q *AppQuery) Select(fields ...string) *AppSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &AppSelect{AppQuery: _q}
	sbuild.label = app.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a AppSelect configured with the given aggregations.
func (_q *AppQuery) Aggregate(fns ...AggregateFunc) *AppSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *AppQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("db: uninitialized interceptor (forgotten import db/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !app.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *AppQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*App, error) {
	var (
		nodes       = []*App{}
		_spec       = _q.querySpec()
		loadedTypes = [6]bool{
			_q.withSites != nil,
			_q.withContainers != nil,
			_q.withDeploys != nil,
			_q.withEnvVars != nil,
			_q.withVolumes != nil,
			_q.withCurrentContainer != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*App).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &App{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withSites; query != nil {
		if err := _q.loadSites(ctx, query, nodes,
			func(n *App) { n.Edges.Sites = []*Site{} },
			func(n *App, e *Site) { n.Edges.Sites = append(n.Edges.Sites, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withContainers; query != nil {
		if err := _q.loadContainers(ctx, query, nodes,
			func(n *App) { n.Edges.Containers = []*Container{} },
			func(n *App, e *Container) { n.Edges.Containers = append(n.Edges.Containers, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDeploys; query != nil {
		if err := _q.loadDeploys(ctx, query, nodes,
			func(n *App) { n.Edges.Deploys = []*Deploy{} },
			func(n *App, e *Deploy) { n.Edges.Deploys = append(n.Edges.Deploys, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withEnvVars; query != nil {
		if err := _q.loadEnvVars(ctx, query, nodes,
			func(n *App) { n.Edges.EnvVars = []*EnvVar{} },
			func(n *App, e *EnvVar) { n.Edges.EnvVars = append(n.Edges.EnvVars, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withVolumes; query != nil {
		if err := _q.loadVolumes(ctx, query, nodes,
			func(n *App) { n.Edges.Volumes = []*Volume{} },
			func(n *App, e *Volume) { n.Edges.Volumes = append(n.Edges.Volumes, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withCurrentContainer; query != nil {
		if err := _q.loadCurrentContainer(ctx, query, nodes, nil,
			func(n *App, e *Container) { n.Edges.CurrentContainer = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *AppQuery) loadSites(ctx context.Context, query *SiteQuery, nodes []*App, init func(*App), assign func(*App, *Site)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Site(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.SitesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_sites
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_sites" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_sites" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AppQuery) loadContainers(ctx context.Context, query *ContainerQuery, nodes []*App, init func(*App), assign func(*App, *Container)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Container(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.ContainersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_containers
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_containers" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_containers" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AppQuery) loadDeploys(ctx context.Context, query *DeployQuery, nodes []*App, init func(*App), assign func(*App, *Deploy)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Deploy(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.DeploysColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_deploys
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_deploys" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_deploys" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AppQuery) loadEnvVars(ctx context.Context, query *EnvVarQuery, nodes []*App, init func(*App), assign func(*App, *EnvVar)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.EnvVar(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.EnvVarsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_env_vars
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_env_vars" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_env_vars" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AppQuery) loadVolumes(ctx context.Context, query *VolumeQuery, nodes []*App, init func(*App), assign func(*App, *Volume)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.Volume(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.VolumesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_volumes
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_volumes" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_volumes" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *AppQuery) loadCurrentContainer(ctx context.Context, query *ContainerQuery, nodes []*App, init func(*App), assign func(*App, *Container)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[int]*App)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
	}
	query.withFKs = true
	query.Where(predicate.Container(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(app.CurrentContainerColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.app_current_container
		if fk == nil {
			return fmt.Errorf(`foreign-key "app_current_container" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "app_current_container" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *AppQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *AppQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(app.Table, app.Columns, sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, app.FieldID)
		for i := range fields {
			if fields[i] != app.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *AppQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(app.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = app.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// AppGroupBy is the group-by builder for App entities.
type AppGroupBy struct {
	selector
	build *AppQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *AppGroupBy) Aggregate(fns ...AggregateFunc) *AppGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *AppGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppQuery, *AppGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *AppGroupBy) sqlScan(ctx context.Context, root *AppQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// AppSelect is the builder for selecting fields of App entities.
type AppSelect struct {
	*AppQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *AppSelect) Aggregate(fns ...AggregateFunc) *AppSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *AppSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*AppQuery, *AppSelect](ctx, _s.AppQuery, _s, _s.inters, v)
}

func (_s *AppSelect) sqlScan(ctx context.Context, root *AppQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
