// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// ContainerUpdate is the builder for updating Container entities.
type ContainerUpdate struct {
	config
	hooks    []Hook
	mutation *ContainerMutation
}

// Where appends a list predicates to the ContainerUpdate builder.
func (_u *ContainerUpdate) Where(ps ...predicate.Container) *ContainerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContainerUpdate) SetUpdatedAt(v time.Time) *ContainerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDockerID sets the "docker_id" field.
func (_u *ContainerUpdate) SetDockerID(v string) *ContainerUpdate {
	_u.mutation.SetDockerID(v)
	return _u
}

// SetNillableDockerID sets the "docker_id" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableDockerID(v *string) *ContainerUpdate {
	if v != nil {
		_u.SetDockerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContainerUpdate) SetName(v string) *ContainerUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableName(v *string) *ContainerUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ContainerUpdate) SetImage(v string) *ContainerUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableImage(v *string) *ContainerUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContainerUpdate) SetStatus(v container.Status) *ContainerUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableStatus(v *container.Status) *ContainerUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ContainerUpdate) SetStartedAt(v time.Time) *ContainerUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableStartedAt(v *time.Time) *ContainerUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ContainerUpdate) ClearStartedAt() *ContainerUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *ContainerUpdate) SetStoppedAt(v time.Time) *ContainerUpdate {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *ContainerUpdate) SetNillableStoppedAt(v *time.Time) *ContainerUpdate {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *ContainerUpdate) ClearStoppedAt() *ContainerUpdate {
	_u.mutation.ClearStoppedAt()
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *ContainerUpdate) SetAppID(id int) *ContainerUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *ContainerUpdate) SetNillableAppID(id *int) *ContainerUpdate {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *ContainerUpdate) SetApp(v *App) *ContainerUpdate {
	return _u.SetAppID(v.ID)
}

// SetDeployID sets the "deploy" edge to the Deploy entity by ID.
func (_u *ContainerUpdate) SetDeployID(id int) *ContainerUpdate {
	_u.mutation.SetDeployID(id)
	return _u
}

// SetNillableDeployID sets the "deploy" edge to the Deploy entity by ID if the given value is not nil.
func (_u *ContainerUpdate) SetNillableDeployID(id *int) *ContainerUpdate {
	if id != nil {
		_u = _u.SetDeployID(*id)
	}
	return _u
}

// SetDeploy sets the "deploy" edge to the Deploy entity.
func (_u *ContainerUpdate) SetDeploy(v *Deploy) *ContainerUpdate {
	return _u.SetDeployID(v.ID)
}

// SetCurrentForID sets the "current_for" edge to the App entity by ID.
func (_u *ContainerUpdate) SetCurrentForID(id int) *ContainerUpdate {
	_u.mutation.SetCurrentForID(id)
	return _u
}

// SetNillableCurrentForID sets the "current_for" edge to the App entity by ID if the given value is not nil.
func (_u *ContainerUpdate) SetNillableCurrentForID(id *int) *ContainerUpdate {
	if id != nil {
		_u = _u.SetCurrentForID(*id)
	}
	return _u
}

// SetCurrentFor sets the "current_for" edge to the App entity.
func (_u *ContainerUpdate) SetCurrentFor(v *App) *ContainerUpdate {
	return _u.SetCurrentForID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_u *ContainerUpdate) Mutation() *ContainerMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *ContainerUpdate) ClearApp() *ContainerUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearDeploy clears the "deploy" edge to the Deploy entity.
func (_u *ContainerUpdate) ClearDeploy() *ContainerUpdate {
	_u.mutation.ClearDeploy()
	return _u
}

// ClearCurrentFor clears the "current_for" edge to the App entity.
func (_u *ContainerUpdate) ClearCurrentFor() *ContainerUpdate {
	_u.mutation.ClearCurrentFor()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ContainerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContainerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ContainerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContainerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContainerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := container.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContainerUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := container.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Container.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ContainerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(container.Table, container.Columns, sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DockerID(); ok {
		_spec.SetField(container.FieldDockerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(container.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(container.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(container.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(container.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(container.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(container.FieldStoppedAt, field.TypeTime)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.AppTable,
			Columns: []string{container.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.AppTable,
			Columns: []string{container.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.DeployTable,
			Columns: []string{container.DeployColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.DeployTable,
			Columns: []string{container.DeployColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentForCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.CurrentForTable,
			Columns: []string{container.CurrentForColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentForIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.CurrentForTable,
			Columns: []string{container.CurrentForColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{container.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ContainerUpdateOne is the builder for updating a single Container entity.
type ContainerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ContainerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ContainerUpdateOne) SetUpdatedAt(v time.Time) *ContainerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDockerID sets the "docker_id" field.
func (_u *ContainerUpdateOne) SetDockerID(v string) *ContainerUpdateOne {
	_u.mutation.SetDockerID(v)
	return _u
}

// SetNillableDockerID sets the "docker_id" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableDockerID(v *string) *ContainerUpdateOne {
	if v != nil {
		_u.SetDockerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *ContainerUpdateOne) SetName(v string) *ContainerUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableName(v *string) *ContainerUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetImage sets the "image" field.
func (_u *ContainerUpdateOne) SetImage(v string) *ContainerUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableImage(v *string) *ContainerUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *ContainerUpdateOne) SetStatus(v container.Status) *ContainerUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableStatus(v *container.Status) *ContainerUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *ContainerUpdateOne) SetStartedAt(v time.Time) *ContainerUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableStartedAt(v *time.Time) *ContainerUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *ContainerUpdateOne) ClearStartedAt() *ContainerUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetStoppedAt sets the "stopped_at" field.
func (_u *ContainerUpdateOne) SetStoppedAt(v time.Time) *ContainerUpdateOne {
	_u.mutation.SetStoppedAt(v)
	return _u
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableStoppedAt(v *time.Time) *ContainerUpdateOne {
	if v != nil {
		_u.SetStoppedAt(*v)
	}
	return _u
}

// ClearStoppedAt clears the value of the "stopped_at" field.
func (_u *ContainerUpdateOne) ClearStoppedAt() *ContainerUpdateOne {
	_u.mutation.ClearStoppedAt()
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *ContainerUpdateOne) SetAppID(id int) *ContainerUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableAppID(id *int) *ContainerUpdateOne {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *ContainerUpdateOne) SetApp(v *App) *ContainerUpdateOne {
	return _u.SetAppID(v.ID)
}

// SetDeployID sets the "deploy" edge to the Deploy entity by ID.
func (_u *ContainerUpdateOne) SetDeployID(id int) *ContainerUpdateOne {
	_u.mutation.SetDeployID(id)
	return _u
}

// SetNillableDeployID sets the "deploy" edge to the Deploy entity by ID if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableDeployID(id *int) *ContainerUpdateOne {
	if id != nil {
		_u = _u.SetDeployID(*id)
	}
	return _u
}

// SetDeploy sets the "deploy" edge to the Deploy entity.
func (_u *ContainerUpdateOne) SetDeploy(v *Deploy) *ContainerUpdateOne {
	return _u.SetDeployID(v.ID)
}

// SetCurrentForID sets the "current_for" edge to the App entity by ID.
func (_u *ContainerUpdateOne) SetCurrentForID(id int) *ContainerUpdateOne {
	_u.mutation.SetCurrentForID(id)
	return _u
}

// SetNillableCurrentForID sets the "current_for" edge to the App entity by ID if the given value is not nil.
func (_u *ContainerUpdateOne) SetNillableCurrentForID(id *int) *ContainerUpdateOne {
	if id != nil {
		_u = _u.SetCurrentForID(*id)
	}
	return _u
}

// SetCurrentFor sets the "current_for" edge to the App entity.
func (_u *ContainerUpdateOne) SetCurrentFor(v *App) *ContainerUpdateOne {
	return _u.SetCurrentForID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_u *ContainerUpdateOne) Mutation() *ContainerMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *ContainerUpdateOne) ClearApp() *ContainerUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearDeploy clears the "deploy" edge to the Deploy entity.
func (_u *ContainerUpdateOne) ClearDeploy() *ContainerUpdateOne {
	_u.mutation.ClearDeploy()
	return _u
}

// ClearCurrentFor clears the "current_for" edge to the App entity.
func (_u *ContainerUpdateOne) ClearCurrentFor() *ContainerUpdateOne {
	_u.mutation.ClearCurrentFor()
	return _u
}

// Where appends a list predicates to the ContainerUpdate builder.
func (_u *ContainerUpdateOne) Where(ps ...predicate.Container) *ContainerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ContainerUpdateOne) Select(field string, fields ...string) *ContainerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Container entity.
func (_u *ContainerUpdateOne) Save(ctx context.Context) (*Container, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ContainerUpdateOne) SaveX(ctx context.Context) *Container {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ContainerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ContainerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ContainerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := container.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ContainerUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := container.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Container.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ContainerUpdateOne) sqlSave(ctx context.Context) (_node *Container, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(container.Table, container.Columns, sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Container.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, container.FieldID)
		for _, f := range fields {
			if !container.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != container.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DockerID(); ok {
		_spec.SetField(container.FieldDockerID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(container.FieldImage, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(container.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(container.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(container.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.StoppedAt(); ok {
		_spec.SetField(container.FieldStoppedAt, field.TypeTime, value)
	}
	if _u.mutation.StoppedAtCleared() {
		_spec.ClearField(container.FieldStoppedAt, field.TypeTime)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.AppTable,
			Columns: []string{container.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.AppTable,
			Columns: []string{container.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.DeployCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.DeployTable,
			Columns: []string{container.DeployColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.DeployIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.DeployTable,
			Columns: []string{container.DeployColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.CurrentForCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.CurrentForTable,
			Columns: []string{container.CurrentForColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.CurrentForIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.CurrentForTable,
			Columns: []string{container.CurrentForColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Container{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{container.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
