// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
)

// ContainerCreate is the builder for creating a Container entity.
type ContainerCreate struct {
	config
	mutation *ContainerMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *ContainerCreate) SetCreatedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableCreatedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *ContainerCreate) SetUpdatedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableUpdatedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDockerID sets the "docker_id" field.
func (_c *ContainerCreate) SetDockerID(v string) *ContainerCreate {
	_c.mutation.SetDockerID(v)
	return _c
}

// SetNillableDockerID sets the "docker_id" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableDockerID(v *string) *ContainerCreate {
	if v != nil {
		_c.SetDockerID(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *ContainerCreate) SetName(v string) *ContainerCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetImage sets the "image" field.
func (_c *ContainerCreate) SetImage(v string) *ContainerCreate {
	_c.mutation.SetImage(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ContainerCreate) SetStatus(v container.Status) *ContainerCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *ContainerCreate) SetStartedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableStartedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetStoppedAt sets the "stopped_at" field.
func (_c *ContainerCreate) SetStoppedAt(v time.Time) *ContainerCreate {
	_c.mutation.SetStoppedAt(v)
	return _c
}

// SetNillableStoppedAt sets the "stopped_at" field if the given value is not nil.
func (_c *ContainerCreate) SetNillableStoppedAt(v *time.Time) *ContainerCreate {
	if v != nil {
		_c.SetStoppedAt(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *ContainerCreate) SetAppID(id int) *ContainerCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_c *ContainerCreate) SetNillableAppID(id *int) *ContainerCreate {
	if id != nil {
		_c = _c.SetAppID(*id)
	}
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *ContainerCreate) SetApp(v *App) *ContainerCreate {
	return _c.SetAppID(v.ID)
}

// SetDeployID sets the "deploy" edge to the Deploy entity by ID.
func (_c *ContainerCreate) SetDeployID(id int) *ContainerCreate {
	_c.mutation.SetDeployID(id)
	return _c
}

// SetNillableDeployID sets the "deploy" edge to the Deploy entity by ID if the given value is not nil.
func (_c *ContainerCreate) SetNillableDeployID(id *int) *ContainerCreate {
	if id != nil {
		_c = _c.SetDeployID(*id)
	}
	return _c
}

// SetDeploy sets the "deploy" edge to the Deploy entity.
func (_c *ContainerCreate) SetDeploy(v *Deploy) *ContainerCreate {
	return _c.SetDeployID(v.ID)
}

// SetCurrentForID sets the "current_for" edge to the App entity by ID.
func (_c *ContainerCreate) SetCurrentForID(id int) *ContainerCreate {
	_c.mutation.SetCurrentForID(id)
	return _c
}

// SetNillableCurrentForID sets the "current_for" edge to the App entity by ID if the given value is not nil.
func (_c *ContainerCreate) SetNillableCurrentForID(id *int) *ContainerCreate {
	if id != nil {
		_c = _c.SetCurrentForID(*id)
	}
	return _c
}

// SetCurrentFor sets the "current_for" edge to the App entity.
func (_c *ContainerCreate) SetCurrentFor(v *App) *ContainerCreate {
	return _c.SetCurrentForID(v.ID)
}

// Mutation returns the ContainerMutation object of the builder.
func (_c *ContainerCreate) Mutation() *ContainerMutation {
	return _c.mutation
}

// Save creates the Container in the database.
func (_c *ContainerCreate) Save(ctx context.Context) (*Container, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ContainerCreate) SaveX(ctx context.Context) *Container {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ContainerCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := container.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := container.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ContainerCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Container.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Container.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`db: missing required field "Container.name"`)}
	}
	if _, ok := _c.mutation.Image(); !ok {
		return &ValidationError{Name: "image", err: errors.New(`db: missing required field "Container.image"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`db: missing required field "Container.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := container.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Container.status": %w`, err)}
		}
	}
	return nil
}

func (_c *ContainerCreate) sqlSave(ctx context.Context) (*Container, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ContainerCreate) createSpec() (*Container, *sqlgraph.CreateSpec) {
	var (
		_node = &Container{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(container.Table, sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(container.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(container.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DockerID(); ok {
		_spec.SetField(container.FieldDockerID, field.TypeString, value)
		_node.DockerID = &value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(container.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Image(); ok {
		_spec.SetField(container.FieldImage, field.TypeString, value)
		_node.Image = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(container.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(container.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.StoppedAt(); ok {
		_spec.SetField(container.FieldStoppedAt, field.TypeTime, value)
		_node.StoppedAt = &value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   container.AppTable,
			Columns: []string{container.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_containers = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.DeployIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.DeployTable,
			Columns: []string{container.DeployColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.deploy_container = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CurrentForIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   container.CurrentForTable,
			Columns: []string{container.CurrentForColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_current_container = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ContainerCreateBulk is the builder for creating many Container entities in bulk.
type ContainerCreateBulk struct {
	config
	err      error
	builders []*ContainerCreate
}

// Save creates the Container entities in the database.
func (_c *ContainerCreateBulk) Save(ctx context.Context) ([]*Container, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Container, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContainerMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ContainerCreateBulk) SaveX(ctx context.Context) []*Container {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ContainerCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ContainerCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
