// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// DeployUpdate is the builder for updating Deploy entities.
type DeployUpdate struct {
	config
	hooks    []Hook
	mutation *DeployMutation
}

// Where appends a list predicates to the DeployUpdate builder.
func (_u *DeployUpdate) Where(ps ...predicate.Deploy) *DeployUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployUpdate) SetUpdatedAt(v time.Time) *DeployUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCommitSha sets the "commit_sha" field.
func (_u *DeployUpdate) SetCommitSha(v string) *DeployUpdate {
	_u.mutation.SetCommitSha(v)
	return _u
}

// SetNillableCommitSha sets the "commit_sha" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableCommitSha(v *string) *DeployUpdate {
	if v != nil {
		_u.SetCommitSha(*v)
	}
	return _u
}

// ClearCommitSha clears the value of the "commit_sha" field.
func (_u *DeployUpdate) ClearCommitSha() *DeployUpdate {
	_u.mutation.ClearCommitSha()
	return _u
}

// SetCommitMessage sets the "commit_message" field.
func (_u *DeployUpdate) SetCommitMessage(v string) *DeployUpdate {
	_u.mutation.SetCommitMessage(v)
	return _u
}

// SetNillableCommitMessage sets the "commit_message" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableCommitMessage(v *string) *DeployUpdate {
	if v != nil {
		_u.SetCommitMessage(*v)
	}
	return _u
}

// ClearCommitMessage clears the value of the "commit_message" field.
func (_u *DeployUpdate) ClearCommitMessage() *DeployUpdate {
	_u.mutation.ClearCommitMessage()
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *DeployUpdate) SetTrigger(v deploy.Trigger) *DeployUpdate {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableTrigger(v *deploy.Trigger) *DeployUpdate {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeployUpdate) SetStatus(v deploy.Status) *DeployUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableStatus(v *deploy.Status) *DeployUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *DeployUpdate) SetError(v string) *DeployUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableError(v *string) *DeployUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *DeployUpdate) ClearError() *DeployUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeployUpdate) SetStartedAt(v time.Time) *DeployUpdate {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableStartedAt(v *time.Time) *DeployUpdate {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeployUpdate) ClearStartedAt() *DeployUpdate {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeployUpdate) SetFinishedAt(v time.Time) *DeployUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableFinishedAt(v *time.Time) *DeployUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeployUpdate) ClearFinishedAt() *DeployUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetImage sets the "image" field.
func (_u *DeployUpdate) SetImage(v string) *DeployUpdate {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DeployUpdate) SetNillableImage(v *string) *DeployUpdate {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DeployUpdate) ClearImage() *DeployUpdate {
	_u.mutation.ClearImage()
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *DeployUpdate) SetAppID(id int) *DeployUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *DeployUpdate) SetNillableAppID(id *int) *DeployUpdate {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *DeployUpdate) SetApp(v *App) *DeployUpdate {
	return _u.SetAppID(v.ID)
}

// SetContainerID sets the "container" edge to the Container entity by ID.
func (_u *DeployUpdate) SetContainerID(id int) *DeployUpdate {
	_u.mutation.SetContainerID(id)
	return _u
}

// SetNillableContainerID sets the "container" edge to the Container entity by ID if the given value is not nil.
func (_u *DeployUpdate) SetNillableContainerID(id *int) *DeployUpdate {
	if id != nil {
		_u = _u.SetContainerID(*id)
	}
	return _u
}

// SetContainer sets the "container" edge to the Container entity.
func (_u *DeployUpdate) SetContainer(v *Container) *DeployUpdate {
	return _u.SetContainerID(v.ID)
}

// Mutation returns the DeployMutation object of the builder.
func (_u *DeployUpdate) Mutation() *DeployMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *DeployUpdate) ClearApp() *DeployUpdate {
	_u.mutation.ClearApp()
	return _u
}

// ClearContainer clears the "container" edge to the Container entity.
func (_u *DeployUpdate) ClearContainer() *DeployUpdate {
	_u.mutation.ClearContainer()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DeployUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DeployUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployUpdate) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := deploy.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`db: validator failed for field "Deploy.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deploy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Deploy.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploy.Table, deploy.Columns, sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommitSha(); ok {
		_spec.SetField(deploy.FieldCommitSha, field.TypeString, value)
	}
	if _u.mutation.CommitShaCleared() {
		_spec.ClearField(deploy.FieldCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.CommitMessage(); ok {
		_spec.SetField(deploy.FieldCommitMessage, field.TypeString, value)
	}
	if _u.mutation.CommitMessageCleared() {
		_spec.ClearField(deploy.FieldCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(deploy.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deploy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(deploy.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(deploy.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploy.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploy.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deploy.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deploy.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(deploy.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(deploy.FieldImage, field.TypeString)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploy.AppTable,
			Columns: []string{deploy.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploy.AppTable,
			Columns: []string{deploy.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   deploy.ContainerTable,
			Columns: []string{deploy.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   deploy.ContainerTable,
			Columns: []string{deploy.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DeployUpdateOne is the builder for updating a single Deploy entity.
type DeployUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DeployMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DeployUpdateOne) SetUpdatedAt(v time.Time) *DeployUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetCommitSha sets the "commit_sha" field.
func (_u *DeployUpdateOne) SetCommitSha(v string) *DeployUpdateOne {
	_u.mutation.SetCommitSha(v)
	return _u
}

// SetNillableCommitSha sets the "commit_sha" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableCommitSha(v *string) *DeployUpdateOne {
	if v != nil {
		_u.SetCommitSha(*v)
	}
	return _u
}

// ClearCommitSha clears the value of the "commit_sha" field.
func (_u *DeployUpdateOne) ClearCommitSha() *DeployUpdateOne {
	_u.mutation.ClearCommitSha()
	return _u
}

// SetCommitMessage sets the "commit_message" field.
func (_u *DeployUpdateOne) SetCommitMessage(v string) *DeployUpdateOne {
	_u.mutation.SetCommitMessage(v)
	return _u
}

// SetNillableCommitMessage sets the "commit_message" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableCommitMessage(v *string) *DeployUpdateOne {
	if v != nil {
		_u.SetCommitMessage(*v)
	}
	return _u
}

// ClearCommitMessage clears the value of the "commit_message" field.
func (_u *DeployUpdateOne) ClearCommitMessage() *DeployUpdateOne {
	_u.mutation.ClearCommitMessage()
	return _u
}

// SetTrigger sets the "trigger" field.
func (_u *DeployUpdateOne) SetTrigger(v deploy.Trigger) *DeployUpdateOne {
	_u.mutation.SetTrigger(v)
	return _u
}

// SetNillableTrigger sets the "trigger" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableTrigger(v *deploy.Trigger) *DeployUpdateOne {
	if v != nil {
		_u.SetTrigger(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *DeployUpdateOne) SetStatus(v deploy.Status) *DeployUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableStatus(v *deploy.Status) *DeployUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetError sets the "error" field.
func (_u *DeployUpdateOne) SetError(v string) *DeployUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableError(v *string) *DeployUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *DeployUpdateOne) ClearError() *DeployUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetStartedAt sets the "started_at" field.
func (_u *DeployUpdateOne) SetStartedAt(v time.Time) *DeployUpdateOne {
	_u.mutation.SetStartedAt(v)
	return _u
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableStartedAt(v *time.Time) *DeployUpdateOne {
	if v != nil {
		_u.SetStartedAt(*v)
	}
	return _u
}

// ClearStartedAt clears the value of the "started_at" field.
func (_u *DeployUpdateOne) ClearStartedAt() *DeployUpdateOne {
	_u.mutation.ClearStartedAt()
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *DeployUpdateOne) SetFinishedAt(v time.Time) *DeployUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableFinishedAt(v *time.Time) *DeployUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *DeployUpdateOne) ClearFinishedAt() *DeployUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetImage sets the "image" field.
func (_u *DeployUpdateOne) SetImage(v string) *DeployUpdateOne {
	_u.mutation.SetImage(v)
	return _u
}

// SetNillableImage sets the "image" field if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableImage(v *string) *DeployUpdateOne {
	if v != nil {
		_u.SetImage(*v)
	}
	return _u
}

// ClearImage clears the value of the "image" field.
func (_u *DeployUpdateOne) ClearImage() *DeployUpdateOne {
	_u.mutation.ClearImage()
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *DeployUpdateOne) SetAppID(id int) *DeployUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableAppID(id *int) *DeployUpdateOne {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *DeployUpdateOne) SetApp(v *App) *DeployUpdateOne {
	return _u.SetAppID(v.ID)
}

// SetContainerID sets the "container" edge to the Container entity by ID.
func (_u *DeployUpdateOne) SetContainerID(id int) *DeployUpdateOne {
	_u.mutation.SetContainerID(id)
	return _u
}

// SetNillableContainerID sets the "container" edge to the Container entity by ID if the given value is not nil.
func (_u *DeployUpdateOne) SetNillableContainerID(id *int) *DeployUpdateOne {
	if id != nil {
		_u = _u.SetContainerID(*id)
	}
	return _u
}

// SetContainer sets the "container" edge to the Container entity.
func (_u *DeployUpdateOne) SetContainer(v *Container) *DeployUpdateOne {
	return _u.SetContainerID(v.ID)
}

// Mutation returns the DeployMutation object of the builder.
func (_u *DeployUpdateOne) Mutation() *DeployMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *DeployUpdateOne) ClearApp() *DeployUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// ClearContainer clears the "container" edge to the Container entity.
func (_u *DeployUpdateOne) ClearContainer() *DeployUpdateOne {
	_u.mutation.ClearContainer()
	return _u
}

// Where appends a list predicates to the DeployUpdate builder.
func (_u *DeployUpdateOne) Where(ps ...predicate.Deploy) *DeployUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DeployUpdateOne) Select(field string, fields ...string) *DeployUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Deploy entity.
func (_u *DeployUpdateOne) Save(ctx context.Context) (*Deploy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DeployUpdateOne) SaveX(ctx context.Context) *Deploy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DeployUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DeployUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DeployUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := deploy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *DeployUpdateOne) check() error {
	if v, ok := _u.mutation.Trigger(); ok {
		if err := deploy.TriggerValidator(v); err != nil {
			return &ValidationError{Name: "trigger", err: fmt.Errorf(`db: validator failed for field "Deploy.trigger": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := deploy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`db: validator failed for field "Deploy.status": %w`, err)}
		}
	}
	return nil
}

func (_u *DeployUpdateOne) sqlSave(ctx context.Context) (_node *Deploy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(deploy.Table, deploy.Columns, sqlgraph.NewFieldSpec(deploy.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Deploy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, deploy.FieldID)
		for _, f := range fields {
			if !deploy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != deploy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(deploy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CommitSha(); ok {
		_spec.SetField(deploy.FieldCommitSha, field.TypeString, value)
	}
	if _u.mutation.CommitShaCleared() {
		_spec.ClearField(deploy.FieldCommitSha, field.TypeString)
	}
	if value, ok := _u.mutation.CommitMessage(); ok {
		_spec.SetField(deploy.FieldCommitMessage, field.TypeString, value)
	}
	if _u.mutation.CommitMessageCleared() {
		_spec.ClearField(deploy.FieldCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Trigger(); ok {
		_spec.SetField(deploy.FieldTrigger, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(deploy.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(deploy.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(deploy.FieldError, field.TypeString)
	}
	if value, ok := _u.mutation.StartedAt(); ok {
		_spec.SetField(deploy.FieldStartedAt, field.TypeTime, value)
	}
	if _u.mutation.StartedAtCleared() {
		_spec.ClearField(deploy.FieldStartedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(deploy.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(deploy.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Image(); ok {
		_spec.SetField(deploy.FieldImage, field.TypeString, value)
	}
	if _u.mutation.ImageCleared() {
		_spec.ClearField(deploy.FieldImage, field.TypeString)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploy.AppTable,
			Columns: []string{deploy.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   deploy.AppTable,
			Columns: []string{deploy.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ContainerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   deploy.ContainerTable,
			Columns: []string{deploy.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ContainerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   deploy.ContainerTable,
			Columns: []string{deploy.ContainerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(container.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Deploy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{deploy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
