// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/envvar"
	"github.com/isaced/nanoku/internal/db/predicate"
)

// EnvVarUpdate is the builder for updating EnvVar entities.
type EnvVarUpdate struct {
	config
	hooks    []Hook
	mutation *EnvVarMutation
}

// Where appends a list predicates to the EnvVarUpdate builder.
func (_u *EnvVarUpdate) Where(ps ...predicate.EnvVar) *EnvVarUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvVarUpdate) SetUpdatedAt(v time.Time) *EnvVarUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *EnvVarUpdate) SetKey(v string) *EnvVarUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableKey(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EnvVarUpdate) SetValue(v string) *EnvVarUpdate {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableValue(v *string) *EnvVarUpdate {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *EnvVarUpdate) SetAppID(id int) *EnvVarUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *EnvVarUpdate) SetNillableAppID(id *int) *EnvVarUpdate {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *EnvVarUpdate) SetApp(v *App) *EnvVarUpdate {
	return _u.SetAppID(v.ID)
}

// Mutation returns the EnvVarMutation object of the builder.
func (_u *EnvVarUpdate) Mutation() *EnvVarMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *EnvVarUpdate) ClearApp() *EnvVarUpdate {
	_u.mutation.ClearApp()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *EnvVarUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvVarUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *EnvVarUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvVarUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvVarUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := envvar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvVarUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := envvar.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`db: validator failed for field "EnvVar.key": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvVarUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envvar.Table, envvar.Columns, sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(envvar.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(envvar.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(envvar.FieldValue, field.TypeString, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envvar.AppTable,
			Columns: []string{envvar.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envvar.AppTable,
			Columns: []string{envvar.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envvar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// EnvVarUpdateOne is the builder for updating a single EnvVar entity.
type EnvVarUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EnvVarMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *EnvVarUpdateOne) SetUpdatedAt(v time.Time) *EnvVarUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *EnvVarUpdateOne) SetKey(v string) *EnvVarUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableKey(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetValue sets the "value" field.
func (_u *EnvVarUpdateOne) SetValue(v string) *EnvVarUpdateOne {
	_u.mutation.SetValue(v)
	return _u
}

// SetNillableValue sets the "value" field if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableValue(v *string) *EnvVarUpdateOne {
	if v != nil {
		_u.SetValue(*v)
	}
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *EnvVarUpdateOne) SetAppID(id int) *EnvVarUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *EnvVarUpdateOne) SetNillableAppID(id *int) *EnvVarUpdateOne {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *EnvVarUpdateOne) SetApp(v *App) *EnvVarUpdateOne {
	return _u.SetAppID(v.ID)
}

// Mutation returns the EnvVarMutation object of the builder.
func (_u *EnvVarUpdateOne) Mutation() *EnvVarMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *EnvVarUpdateOne) ClearApp() *EnvVarUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// Where appends a list predicates to the EnvVarUpdate builder.
func (_u *EnvVarUpdateOne) Where(ps ...predicate.EnvVar) *EnvVarUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *EnvVarUpdateOne) Select(field string, fields ...string) *EnvVarUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated EnvVar entity.
func (_u *EnvVarUpdateOne) Save(ctx context.Context) (*EnvVar, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *EnvVarUpdateOne) SaveX(ctx context.Context) *EnvVar {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *EnvVarUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *EnvVarUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *EnvVarUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := envvar.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *EnvVarUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := envvar.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`db: validator failed for field "EnvVar.key": %w`, err)}
		}
	}
	return nil
}

func (_u *EnvVarUpdateOne) sqlSave(ctx context.Context) (_node *EnvVar, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(envvar.Table, envvar.Columns, sqlgraph.NewFieldSpec(envvar.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "EnvVar.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, envvar.FieldID)
		for _, f := range fields {
			if !envvar.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != envvar.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(envvar.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(envvar.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Value(); ok {
		_spec.SetField(envvar.FieldValue, field.TypeString, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envvar.AppTable,
			Columns: []string{envvar.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   envvar.AppTable,
			Columns: []string{envvar.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &EnvVar{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{envvar.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
