// Code generated by ent, DO NOT EDIT.

package db

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/envvar"
)

// EnvVar is the model entity for the EnvVar schema.
type EnvVar struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Env var name, e.g. DATABASE_URL.
	Key string `json:"key,omitempty"`
	// Env var value. Plain text in v1; encryption in v2.
	Value string `json:"-"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the EnvVarQuery when eager-loading is set.
	Edges        EnvVarEdges `json:"edges"`
	app_env_vars *int
	selectValues sql.SelectValues
}

// EnvVarEdges holds the relations/edges for other nodes in the graph.
type EnvVarEdges struct {
	// App holds the value of the app edge.
	App *App `json:"app,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AppOrErr returns the App value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e EnvVarEdges) AppOrErr() (*App, error) {
	if e.App != nil {
		return e.App, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: app.Label}
	}
	return nil, &NotLoadedError{edge: "app"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*EnvVar) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case envvar.FieldID:
			values[i] = new(sql.NullInt64)
		case envvar.FieldKey, envvar.FieldValue:
			values[i] = new(sql.NullString)
		case envvar.FieldCreatedAt, envvar.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case envvar.ForeignKeys[0]: // app_env_vars
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the EnvVar fields.
func (_m *EnvVar) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case envvar.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case envvar.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case envvar.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case envvar.FieldKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field key", values[i])
			} else if value.Valid {
				_m.Key = value.String
			}
		case envvar.FieldValue:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field value", values[i])
			} else if value.Valid {
				_m.Value = value.String
			}
		case envvar.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field app_env_vars", value)
			} else if value.Valid {
				_m.app_env_vars = new(int)
				*_m.app_env_vars = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// GetValue returns the ent.Value that was dynamically selected and assigned to the EnvVar.
// This includes values selected through modifiers, order, etc.
func (_m *EnvVar) GetValue(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryApp queries the "app" edge of the EnvVar entity.
func (_m *EnvVar) QueryApp() *AppQuery {
	return NewEnvVarClient(_m.config).QueryApp(_m)
}

// Update returns a builder for updating this EnvVar.
// Note that you need to call EnvVar.Unwrap() before calling this method if this EnvVar
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *EnvVar) Update() *EnvVarUpdateOne {
	return NewEnvVarClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the EnvVar entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *EnvVar) Unwrap() *EnvVar {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("db: EnvVar is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *EnvVar) String() string {
	var builder strings.Builder
	builder.WriteString("EnvVar(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("key=")
	builder.WriteString(_m.Key)
	builder.WriteString(", ")
	builder.WriteString("value=<sensitive>")
	builder.WriteByte(')')
	return builder.String()
}

// EnvVars is a parsable slice of EnvVar.
type EnvVars []*EnvVar
