// Code generated by ent, DO NOT EDIT.

package db

import (
	"time"

	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/container"
	"github.com/isaced/nanoku/internal/db/deploy"
	"github.com/isaced/nanoku/internal/db/envvar"
	"github.com/isaced/nanoku/internal/db/schema"
	"github.com/isaced/nanoku/internal/db/site"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	appMixin := schema.App{}.Mixin()
	appMixinFields0 := appMixin[0].Fields()
	_ = appMixinFields0
	appFields := schema.App{}.Fields()
	_ = appFields
	// appDescCreatedAt is the schema descriptor for created_at field.
	appDescCreatedAt := appMixinFields0[0].Descriptor()
	// app.DefaultCreatedAt holds the default value on creation for the created_at field.
	app.DefaultCreatedAt = appDescCreatedAt.Default.(func() time.Time)
	// appDescUpdatedAt is the schema descriptor for updated_at field.
	appDescUpdatedAt := appMixinFields0[1].Descriptor()
	// app.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	app.DefaultUpdatedAt = appDescUpdatedAt.Default.(func() time.Time)
	// app.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	app.UpdateDefaultUpdatedAt = appDescUpdatedAt.UpdateDefault.(func() time.Time)
	// appDescName is the schema descriptor for name field.
	appDescName := appFields[0].Descriptor()
	// app.NameValidator is a validator for the "name" field. It is called by the builders before save.
	app.NameValidator = appDescName.Validators[0].(func(string) error)
	// appDescPort is the schema descriptor for port field.
	appDescPort := appFields[2].Descriptor()
	// app.PortValidator is a validator for the "port" field. It is called by the builders before save.
	app.PortValidator = func() func(int) error {
		validators := appDescPort.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(port int) error {
			for _, fn := range fns {
				if err := fn(port); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// appDescBranch is the schema descriptor for branch field.
	appDescBranch := appFields[4].Descriptor()
	// app.DefaultBranch holds the default value on creation for the branch field.
	app.DefaultBranch = appDescBranch.Default.(string)
	// appDescDeployMethod is the schema descriptor for deploy_method field.
	appDescDeployMethod := appFields[5].Descriptor()
	// app.DefaultDeployMethod holds the default value on creation for the deploy_method field.
	app.DefaultDeployMethod = appDescDeployMethod.Default.(string)
	containerMixin := schema.Container{}.Mixin()
	containerMixinFields0 := containerMixin[0].Fields()
	_ = containerMixinFields0
	containerFields := schema.Container{}.Fields()
	_ = containerFields
	// containerDescCreatedAt is the schema descriptor for created_at field.
	containerDescCreatedAt := containerMixinFields0[0].Descriptor()
	// container.DefaultCreatedAt holds the default value on creation for the created_at field.
	container.DefaultCreatedAt = containerDescCreatedAt.Default.(func() time.Time)
	// containerDescUpdatedAt is the schema descriptor for updated_at field.
	containerDescUpdatedAt := containerMixinFields0[1].Descriptor()
	// container.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	container.DefaultUpdatedAt = containerDescUpdatedAt.Default.(func() time.Time)
	// container.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	container.UpdateDefaultUpdatedAt = containerDescUpdatedAt.UpdateDefault.(func() time.Time)
	deployMixin := schema.Deploy{}.Mixin()
	deployMixinFields0 := deployMixin[0].Fields()
	_ = deployMixinFields0
	deployFields := schema.Deploy{}.Fields()
	_ = deployFields
	// deployDescCreatedAt is the schema descriptor for created_at field.
	deployDescCreatedAt := deployMixinFields0[0].Descriptor()
	// deploy.DefaultCreatedAt holds the default value on creation for the created_at field.
	deploy.DefaultCreatedAt = deployDescCreatedAt.Default.(func() time.Time)
	// deployDescUpdatedAt is the schema descriptor for updated_at field.
	deployDescUpdatedAt := deployMixinFields0[1].Descriptor()
	// deploy.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	deploy.DefaultUpdatedAt = deployDescUpdatedAt.Default.(func() time.Time)
	// deploy.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	deploy.UpdateDefaultUpdatedAt = deployDescUpdatedAt.UpdateDefault.(func() time.Time)
	envvarMixin := schema.EnvVar{}.Mixin()
	envvarMixinFields0 := envvarMixin[0].Fields()
	_ = envvarMixinFields0
	envvarFields := schema.EnvVar{}.Fields()
	_ = envvarFields
	// envvarDescCreatedAt is the schema descriptor for created_at field.
	envvarDescCreatedAt := envvarMixinFields0[0].Descriptor()
	// envvar.DefaultCreatedAt holds the default value on creation for the created_at field.
	envvar.DefaultCreatedAt = envvarDescCreatedAt.Default.(func() time.Time)
	// envvarDescUpdatedAt is the schema descriptor for updated_at field.
	envvarDescUpdatedAt := envvarMixinFields0[1].Descriptor()
	// envvar.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	envvar.DefaultUpdatedAt = envvarDescUpdatedAt.Default.(func() time.Time)
	// envvar.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	envvar.UpdateDefaultUpdatedAt = envvarDescUpdatedAt.UpdateDefault.(func() time.Time)
	// envvarDescKey is the schema descriptor for key field.
	envvarDescKey := envvarFields[0].Descriptor()
	// envvar.KeyValidator is a validator for the "key" field. It is called by the builders before save.
	envvar.KeyValidator = envvarDescKey.Validators[0].(func(string) error)
	siteMixin := schema.Site{}.Mixin()
	siteMixinFields0 := siteMixin[0].Fields()
	_ = siteMixinFields0
	siteFields := schema.Site{}.Fields()
	_ = siteFields
	// siteDescCreatedAt is the schema descriptor for created_at field.
	siteDescCreatedAt := siteMixinFields0[0].Descriptor()
	// site.DefaultCreatedAt holds the default value on creation for the created_at field.
	site.DefaultCreatedAt = siteDescCreatedAt.Default.(func() time.Time)
	// siteDescUpdatedAt is the schema descriptor for updated_at field.
	siteDescUpdatedAt := siteMixinFields0[1].Descriptor()
	// site.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	site.DefaultUpdatedAt = siteDescUpdatedAt.Default.(func() time.Time)
	// site.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	site.UpdateDefaultUpdatedAt = siteDescUpdatedAt.UpdateDefault.(func() time.Time)
	// siteDescEnabled is the schema descriptor for enabled field.
	siteDescEnabled := siteFields[2].Descriptor()
	// site.DefaultEnabled holds the default value on creation for the enabled field.
	site.DefaultEnabled = siteDescEnabled.Default.(bool)
}
