// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/predicate"
	"github.com/isaced/nanoku/internal/db/site"
)

// SiteUpdate is the builder for updating Site entities.
type SiteUpdate struct {
	config
	hooks    []Hook
	mutation *SiteMutation
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdate) Where(ps ...predicate.Site) *SiteUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdate) SetUpdatedAt(v time.Time) *SiteUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdate) SetDomain(v string) *SiteUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableDomain(v *string) *SiteUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *SiteUpdate) SetUpstream(v string) *SiteUpdate {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableUpstream(v *string) *SiteUpdate {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SiteUpdate) SetEnabled(v bool) *SiteUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SiteUpdate) SetNillableEnabled(v *bool) *SiteUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *SiteUpdate) SetAppID(id int) *SiteUpdate {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *SiteUpdate) SetNillableAppID(id *int) *SiteUpdate {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *SiteUpdate) SetApp(v *App) *SiteUpdate {
	return _u.SetAppID(v.ID)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdate) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *SiteUpdate) ClearApp() *SiteUpdate {
	_u.mutation.ClearApp()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SiteUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SiteUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SiteUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(site.FieldUpstream, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(site.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   site.AppTable,
			Columns: []string{site.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   site.AppTable,
			Columns: []string{site.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SiteUpdateOne is the builder for updating a single Site entity.
type SiteUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SiteMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SiteUpdateOne) SetUpdatedAt(v time.Time) *SiteUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDomain sets the "domain" field.
func (_u *SiteUpdateOne) SetDomain(v string) *SiteUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableDomain(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// SetUpstream sets the "upstream" field.
func (_u *SiteUpdateOne) SetUpstream(v string) *SiteUpdateOne {
	_u.mutation.SetUpstream(v)
	return _u
}

// SetNillableUpstream sets the "upstream" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableUpstream(v *string) *SiteUpdateOne {
	if v != nil {
		_u.SetUpstream(*v)
	}
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *SiteUpdateOne) SetEnabled(v bool) *SiteUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableEnabled(v *bool) *SiteUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_u *SiteUpdateOne) SetAppID(id int) *SiteUpdateOne {
	_u.mutation.SetAppID(id)
	return _u
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_u *SiteUpdateOne) SetNillableAppID(id *int) *SiteUpdateOne {
	if id != nil {
		_u = _u.SetAppID(*id)
	}
	return _u
}

// SetApp sets the "app" edge to the App entity.
func (_u *SiteUpdateOne) SetApp(v *App) *SiteUpdateOne {
	return _u.SetAppID(v.ID)
}

// Mutation returns the SiteMutation object of the builder.
func (_u *SiteUpdateOne) Mutation() *SiteMutation {
	return _u.mutation
}

// ClearApp clears the "app" edge to the App entity.
func (_u *SiteUpdateOne) ClearApp() *SiteUpdateOne {
	_u.mutation.ClearApp()
	return _u
}

// Where appends a list predicates to the SiteUpdate builder.
func (_u *SiteUpdateOne) Where(ps ...predicate.Site) *SiteUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SiteUpdateOne) Select(field string, fields ...string) *SiteUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Site entity.
func (_u *SiteUpdateOne) Save(ctx context.Context) (*Site, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SiteUpdateOne) SaveX(ctx context.Context) *Site {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SiteUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SiteUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SiteUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := site.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *SiteUpdateOne) sqlSave(ctx context.Context) (_node *Site, err error) {
	_spec := sqlgraph.NewUpdateSpec(site.Table, site.Columns, sqlgraph.NewFieldSpec(site.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`db: missing "Site.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, site.FieldID)
		for _, f := range fields {
			if !site.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("db: invalid field %q for query", f)}
			}
			if f != site.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(site.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(site.FieldDomain, field.TypeString, value)
	}
	if value, ok := _u.mutation.Upstream(); ok {
		_spec.SetField(site.FieldUpstream, field.TypeString, value)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(site.FieldEnabled, field.TypeBool, value)
	}
	if _u.mutation.AppCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   site.AppTable,
			Columns: []string{site.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   site.AppTable,
			Columns: []string{site.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Site{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{site.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
