// Code generated by ent, DO NOT EDIT.

package db

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/isaced/nanoku/internal/db/app"
	"github.com/isaced/nanoku/internal/db/volume"
)

// VolumeCreate is the builder for creating a Volume entity.
type VolumeCreate struct {
	config
	mutation *VolumeMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *VolumeCreate) SetCreatedAt(v time.Time) *VolumeCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VolumeCreate) SetNillableCreatedAt(v *time.Time) *VolumeCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VolumeCreate) SetUpdatedAt(v time.Time) *VolumeCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VolumeCreate) SetNillableUpdatedAt(v *time.Time) *VolumeCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *VolumeCreate) SetType(v volume.Type) *VolumeCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetSource sets the "source" field.
func (_c *VolumeCreate) SetSource(v string) *VolumeCreate {
	_c.mutation.SetSource(v)
	return _c
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_c *VolumeCreate) SetNillableSource(v *string) *VolumeCreate {
	if v != nil {
		_c.SetSource(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *VolumeCreate) SetTarget(v string) *VolumeCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetReadOnly sets the "read_only" field.
func (_c *VolumeCreate) SetReadOnly(v bool) *VolumeCreate {
	_c.mutation.SetReadOnly(v)
	return _c
}

// SetNillableReadOnly sets the "read_only" field if the given value is not nil.
func (_c *VolumeCreate) SetNillableReadOnly(v *bool) *VolumeCreate {
	if v != nil {
		_c.SetReadOnly(*v)
	}
	return _c
}

// SetAppID sets the "app" edge to the App entity by ID.
func (_c *VolumeCreate) SetAppID(id int) *VolumeCreate {
	_c.mutation.SetAppID(id)
	return _c
}

// SetNillableAppID sets the "app" edge to the App entity by ID if the given value is not nil.
func (_c *VolumeCreate) SetNillableAppID(id *int) *VolumeCreate {
	if id != nil {
		_c = _c.SetAppID(*id)
	}
	return _c
}

// SetApp sets the "app" edge to the App entity.
func (_c *VolumeCreate) SetApp(v *App) *VolumeCreate {
	return _c.SetAppID(v.ID)
}

// Mutation returns the VolumeMutation object of the builder.
func (_c *VolumeCreate) Mutation() *VolumeMutation {
	return _c.mutation
}

// Save creates the Volume in the database.
func (_c *VolumeCreate) Save(ctx context.Context) (*Volume, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VolumeCreate) SaveX(ctx context.Context) *Volume {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VolumeCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VolumeCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VolumeCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := volume.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := volume.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ReadOnly(); !ok {
		v := volume.DefaultReadOnly
		_c.mutation.SetReadOnly(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VolumeCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`db: missing required field "Volume.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`db: missing required field "Volume.updated_at"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`db: missing required field "Volume.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := volume.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`db: validator failed for field "Volume.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`db: missing required field "Volume.target"`)}
	}
	if _, ok := _c.mutation.ReadOnly(); !ok {
		return &ValidationError{Name: "read_only", err: errors.New(`db: missing required field "Volume.read_only"`)}
	}
	return nil
}

func (_c *VolumeCreate) sqlSave(ctx context.Context) (*Volume, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VolumeCreate) createSpec() (*Volume, *sqlgraph.CreateSpec) {
	var (
		_node = &Volume{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(volume.Table, sqlgraph.NewFieldSpec(volume.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(volume.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(volume.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(volume.FieldType, field.TypeEnum, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Source(); ok {
		_spec.SetField(volume.FieldSource, field.TypeString, value)
		_node.Source = &value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(volume.FieldTarget, field.TypeString, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.ReadOnly(); ok {
		_spec.SetField(volume.FieldReadOnly, field.TypeBool, value)
		_node.ReadOnly = value
	}
	if nodes := _c.mutation.AppIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   volume.AppTable,
			Columns: []string{volume.AppColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(app.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.app_volumes = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VolumeCreateBulk is the builder for creating many Volume entities in bulk.
type VolumeCreateBulk struct {
	config
	err      error
	builders []*VolumeCreate
}

// Save creates the Volume entities in the database.
func (_c *VolumeCreateBulk) Save(ctx context.Context) ([]*Volume, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Volume, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VolumeMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VolumeCreateBulk) SaveX(ctx context.Context) []*Volume {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VolumeCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VolumeCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
